if("undefined"!==typeof goog)var Apiomat={Status:{}};"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Status={SCRIPT_ERROR:701,APPLICATION_NOT_ACTIVE:702,BAD_IMAGE:703,BAD_ID:704,CONCURRENT_ACCESS:705,APPLICATION_SANDBOX:706,MODEL_NOT_DEPLOYED:707,WRONG_REF_TYPE:709,ATTRIBUTE_NOT_SET:710,OPERATION_NOT_POSSIBLE:711,APPLICATION_NAME_MISMATCH:712,WRONG_AUTH_HEADER:713,MODEL_STILL_USED:714,COLLECTION_NOT_ALLOWED:715,FB_NO_VALID_MEMBER:716,FB_NO_OAUTH_TOKEN:717,FB_POST_ID_MISSING:718,RESTORE_NO_DUMPS_FOUND:719,TW_NO_VALID_MEMBER:720,TW_NO_OAUTH_TOKEN:721,IMEXPORT_WRONG_ENCODING:722,IMEXPORT_WRONG_CONTENT:723,
PUSH_PAYLOAD_EXCEEDED:724,PUSH_ERROR:725,BAD_EMAIL:726,BAD_PROMOTIONCODE_DISCOUNT:727,BAD_PROMOTIONCODE_CODE:728,PLAN_PRICE:729,PLAN_NO_SYSTEMS:730,SCRIPT_TIME_ERROR:731,INVALID_NAME:732,ATTRIBUTE_IN_SUPERCLASS:733,JSON_TYPE_ERROR:734,TBLR_NO_VALID_MEMBER:735,TBLR_NO_OAUTH_TOKEN:736,TBLR_POST_ID_MISSING:737,LOCATION_INVALID:738,SCRIPT_EXCEPTION:739,BAD_ACCOUNTNAME:740,BAD_IMAGE_ALPHA:746,BAD_IMAGE_BGCOLOR:747,BAD_IMAGE_FORMAT:748,QUERY_ERROR:708,BAD_TYPE_IN_QUERY:741,UNKNOWN_CLASS_IN_QUERY:742,WRONG_NUM_FORMAT_IN_QUERY:743,
QUERY_PARSE_ERROR:744,UNKNOWN_ATTRIBUTE_IN_QUERY:745,FOREIGNID_NOT_SET:749,CLASSES_MISSING:750,INVALID_ATTRIBUTE_TYPE:751,TOKEN_VALUE_EXISTS:752,JSON_FORMAT_ERROR:753,MODULE_DEPLOYMENT:754,BAD_USERNAME:755,CSV_ZIP_FORMAT:756,VERIFICATION:757,MODULE_STILL_USED:758,CLASS_NOT_IN_MODULE:759,ORDER_TRANSACTION_TIMESTAMP_OUTDATED:760,ORDER_TRANSACTION_ID_INVALID:761,ORDER_TRANSACTION_SECRET_INVALID:762,MANDATORY_FIELD:763,INVALID_PASSWD_LENGTH:764,BAD_PROMOTIONCODE_VALID:765,BAD_CLASS_NAME_SAME_AS_MODULE:766,
NO_ORG_MEMBER:767,MODULE_CLASS_NOT_CONTAINED:768,BAD_GROUP_NAME:769,INVISIBLE_CLASS:770,MODULE_TYPE_NOT_ALLOWED:771,APPLICATION_NOT_FOUND:801,CUSTOMER_NOT_FOUND:802,ID_NOT_FOUND:803,MODEL_NOT_FOUND:804,MODULE_NOT_FOUND:805,PLAN_NOT_FOUND:807,PROMOCODE_NOT_FOUND:808,DEMOAPP_NOT_FOUND:809,ORGANIZATION_NOT_FOUND:810,GROUP_NOT_FOUND:811,ACCOUNT_NOT_FOUND:812,DEFAULT_MODULE_NOT_FOUND:813,MODULE_USE_FORBIDDEN:820,PUSH_ERROR_APIKEY:821,PUSH_ERROR_CERTIFICATE:822,SAME_NAME_USED_IN_SUPERCLASS:823,PAYMENT_MAX_MODULE:824,
PAYMENT_SYSTEM:825,PAYMENT_DOWNGRADE:826,SAVE_REFERENECE_BEFORE_REFERENCING:827,PAYMENT_DB_SIZE:828,ENDPOINT_PATH_NOT_ALLOWED:829,PAYMENT_NO_CRON:1820,PAYMENT_MODULE_NOT_FREE:1821,NATIVEMODULE_DEACTIVATED:1822,LICENSE_INVALID:1823,PAYMENT_NO_CUSTOMERROLES:1824,WHITELABEL:1825,WHITELABEL_NOT:1826,MODULE_CONFIG_NO_DOT:1827,PLAN_FALLBACK:1828,PLAN_INACTIVE:1829,ENTERPRISE:1830,ACCOUNT_UNACCEPTED_CONTRACTS:1831,DELETE_MANDATORY_DEFAULT_MODULE:1832,ID_EXISTS:830,NAME_RESERVED:831,CIRCULAR_DEPENDENCY:832,
NAME_EXISTS:833,EMAIL_EXISTS:834,CUSTOMER_IN_ORG:835,UNAUTHORIZED:840,WRONG_APIKEY:841,EVALANCHE_UNAUTH:842,PW_CHANGE_W_TOKEN:843,TOKEN_AUTH_ERROR:844,TOKEN_READ_ONLY:845,AUTHENTICATION_REJECTED:846,CRUD_ERROR:901,IMEXPORT_ERROR:902,COMPILE_ERROR:903,REFERENCE_ERROR:904,PUSH_PAYLOAD_ERROR:905,PUSH_SEND_ERROR:906,PUSH_INIT_FAILED:907,FACEBOOK_ERROR:908,FACEBOOK_OAUTH_ERROR:910,FACEBOOK_OAUTH_ERROR2:917,MEMBER_NOT_FOUND:911,WORDPRESS_FETCH_DATA_ERROR:912,TUMBLR_OAUTH_ERROR:913,TUMBLR_ERROR:914,EXECUTE_METHOD_ERROR_PRIMITIVE:915,
EXECUTE_METHOD_ERROR:916,OAUTH_TOKEN_REQUEST_ERROR:918,FINDING_RESOURCE_ERROR:919,NATIVEMODULE_DEPLOY:920,TOKEN_SEARCH_ERROR:921,MODULE_CONFIG_MISSING:922,NATIVEMODULE_INIT:923,NATIVEMODULE_PULL:924,NATIVEMODULE_PUSH:925,NO_DOGET_RETURN:926,CUSTOMER_TWO_ORGS:927,NATIVEMODULE_HOOKS_NOT_FOUND:928,ANALYTICS_ERROR:929,EMAIL_ERROR:930,HREF_NOT_FOUND:601,WRONG_URI_SYNTAX:602,WRONG_CLIENT_PROTOCOL:603,IO_EXCEPTION:604,UNSUPPORTED_ENCODING:605,INSTANTIATE_EXCEPTION:606,IN_PERSISTING_PROCESS:607,VERIFY_SOCIALMEDIA:608,
TOO_MANY_LOCALIDS:609,MAX_CACHE_SIZE_REACHED:610,CANT_WRITE_IN_CACHE:611,BAD_DATASTORE_CONFIG:612,NO_TOKEN_RECEIVED:613,NO_NETWORK:614,ID_NOT_FOUND_OFFLINE:615,ATTACHED_HREF_MISSING:616,REQUEST_TIMEOUT:617,ASYNC_WAIT_ERROR:618,IN_DELETING_PROCESS:619,SSO_REDIRECT:620,MANUAL_CONCURRENT_WRITE_FAILED:621,SAVE_FAILED:622,MALICIOUS_MEMBER:950,getReasonPhrase:function(c){var b=void 0;switch(c){case a.Status.SCRIPT_ERROR:b="Script error!";break;case a.Status.APPLICATION_NOT_ACTIVE:b="Application is deactivated!";
break;case a.Status.BAD_IMAGE:b="Image format seems to be corrupted!";break;case a.Status.BAD_ID:b="ID format is wrong!";break;case a.Status.CONCURRENT_ACCESS:b="Concurrent access forbidden!";break;case a.Status.APPLICATION_SANDBOX:b="Application is in sandbox mode!";break;case a.Status.MODEL_NOT_DEPLOYED:b="Class is not deployed!";break;case a.Status.WRONG_REF_TYPE:b="Wrong reference type!";break;case a.Status.ATTRIBUTE_NOT_SET:b="Attribute not set!";break;case a.Status.OPERATION_NOT_POSSIBLE:b=
"CRUD operation not possible on this class!";break;case a.Status.APPLICATION_NAME_MISMATCH:b="Application name does not match the one defined in the class!";break;case a.Status.WRONG_AUTH_HEADER:b="Wrong authentication header format, must be 'username:password'";break;case a.Status.MODEL_STILL_USED:b="Class is still used by other attributes, scripts or subclasses!'";break;case a.Status.COLLECTION_NOT_ALLOWED:b="Collection is not supported for this class type!";break;case a.Status.FB_NO_VALID_MEMBER:b=
"Request send from no valid member";break;case a.Status.FB_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";break;case a.Status.FB_POST_ID_MISSING:b="Facebook post id has to be set!";break;case a.Status.RESTORE_NO_DUMPS_FOUND:b="No dumps for app on this date exist!";break;case a.Status.TW_NO_VALID_MEMBER:b="Request send from no valid member";break;case a.Status.TW_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";
break;case a.Status.IMEXPORT_WRONG_ENCODING:b="Wrong Encoding";break;case a.Status.IMEXPORT_WRONG_CONTENT:b="Wrong Filecontent";break;case a.Status.PUSH_PAYLOAD_EXCEEDED:b="Payload size exceeded!";break;case a.Status.PUSH_ERROR:b="Error in push request!";break;case a.Status.BAD_EMAIL:b="eMail format is wrong!";break;case a.Status.BAD_PROMOTIONCODE_DISCOUNT:b="Discount value is wrong!";break;case a.Status.BAD_PROMOTIONCODE_CODE:b="Code is invalid";break;case a.Status.PLAN_PRICE:b="Plan price must be \x3e\x3d 0!";
break;case a.Status.PLAN_NO_SYSTEMS:b="Plan must have at least one system!";break;case a.Status.SCRIPT_TIME_ERROR:b="Script was interrupted, execution took too long.";break;case a.Status.INVALID_NAME:b="Name must start with a letter, followed only by letters or numbers.";break;case a.Status.ATTRIBUTE_IN_SUPERCLASS:b="Attribute is already defined in superclass.";break;case a.Status.JSON_TYPE_ERROR:b="The @type is not correctly defined in your JSON (must be: MODULENAME$CLASSNAME";break;case a.Status.TBLR_NO_VALID_MEMBER:b=
"Request send from no valid member";break;case a.Status.TBLR_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";break;case a.Status.TBLR_POST_ID_MISSING:b="Tumblr post id has to be set!";break;case a.Status.LOCATION_INVALID:b="Location data is invalid (latitude or longitude missing)!";break;case a.Status.SCRIPT_EXCEPTION:b="Exception was raised in external code!";break;case a.Status.BAD_ACCOUNTNAME:b="Account name must contain only characters A-Z,a-z or 0-9!";
break;case a.Status.BAD_IMAGE_ALPHA:b="alpha is wrong (must be a double value between 0.0 and 1.0)";break;case a.Status.BAD_IMAGE_BGCOLOR:b="bgcolor is wrong (must be an RGB hex value without #, like 'FF0000' for red)";break;case a.Status.BAD_IMAGE_FORMAT:b="format is wrong (can only be png, gif, bmp or jpg/jpeg)";break;case a.Status.QUERY_ERROR:b="Query could not be parsed!";break;case a.Status.BAD_TYPE_IN_QUERY:b="The query contains a value with the wrong type";break;case a.Status.UNKNOWN_CLASS_IN_QUERY:b=
"The definition of the class couldn't be found";break;case a.Status.WRONG_NUM_FORMAT_IN_QUERY:b="A number was supplied in the wrong format";break;case a.Status.QUERY_PARSE_ERROR:b="The query couldn't be parsed";break;case a.Status.UNKNOWN_ATTRIBUTE_IN_QUERY:b="An attribute that was used in the query doesn't exist in the class";break;case a.Status.FOREIGNID_NOT_SET:b="Foreign ID must be set to a unique value for this class!";break;case a.Status.CLASSES_MISSING:b="Not all classes for this module are contained in the jar! This will lead to compile errors.";
break;case a.Status.INVALID_ATTRIBUTE_TYPE:b="Attributes type is invalid";break;case a.Status.TOKEN_VALUE_EXISTS:b="The token value already exists";break;case a.Status.JSON_FORMAT_ERROR:b="JSON could not be parsed";break;case a.Status.MODULE_DEPLOYMENT:b="Module is currently deploying. Please try again later.";break;case a.Status.BAD_USERNAME:b="User name must not contain a ':'.";break;case a.Status.CSV_ZIP_FORMAT:b="CSV import only accepts a single .zip file!";break;case a.Status.VERIFICATION:b=
"Verification error";break;case a.Status.MODULE_STILL_USED:b="Module is still used by other modules of this app!'";break;case a.Status.CLASS_NOT_IN_MODULE:b="Model name not found for this module!";break;case a.Status.ORDER_TRANSACTION_TIMESTAMP_OUTDATED:b="Transaction outdated!";break;case a.Status.ORDER_TRANSACTION_ID_INVALID:b="Transaction ID invalid!";break;case a.Status.ORDER_TRANSACTION_SECRET_INVALID:b="Transaction secret invalid!";break;case a.Status.MANDATORY_FIELD:b="Mandatory fields must not be empty or null!";
break;case a.Status.INVALID_PASSWD_LENGTH:b="Password must have a length of at least 6 characters!";break;case a.Status.BAD_PROMOTIONCODE_VALID:b="Valid from/to of Code is null";break;case a.Status.BAD_CLASS_NAME_SAME_AS_MODULE:b="Class name must not be the same as the module name!";break;case a.Status.NO_ORG_MEMBER:b="Customer is not a member of the organization";break;case a.Status.MODULE_CLASS_NOT_CONTAINED:b="Module main class is not contained in the uploaded file! Probably wrong module uploaded?";
break;case a.Status.BAD_GROUP_NAME:b="Account name must contain only characters A-Z,a-z or 0-9!";break;case a.Status.INVISIBLE_CLASS:b="Class is not visible to REST!";break;case a.Status.MODULE_TYPE_NOT_ALLOWED:b="The action is not allowed for this module type";break;case a.Status.APPLICATION_NOT_FOUND:b="Application was not found!";break;case a.Status.CUSTOMER_NOT_FOUND:b="Customer was not found!";break;case a.Status.ID_NOT_FOUND:b="ID was not found!";break;case a.Status.MODEL_NOT_FOUND:b="Class was not found!";
break;case a.Status.MODULE_NOT_FOUND:b="Module was not found!";break;case a.Status.PLAN_NOT_FOUND:b="Plan was not found!";break;case a.Status.PROMOCODE_NOT_FOUND:b="Promotion code not valid!";break;case a.Status.DEMOAPP_NOT_FOUND:b="This language has no demo content";break;case a.Status.ORGANIZATION_NOT_FOUND:b="Organization was not found!";break;case a.Status.GROUP_NOT_FOUND:b="Group was not found!";break;case a.Status.ACCOUNT_NOT_FOUND:b="Account was not found!";break;case a.Status.DEFAULT_MODULE_NOT_FOUND:b=
"Default module was not found for the given account";break;case a.Status.MODULE_USE_FORBIDDEN:b="Required module is not attached to app";break;case a.Status.PUSH_ERROR_APIKEY:b="No API Key defined for Push service!";break;case a.Status.PUSH_ERROR_CERTIFICATE:b="No certificate defined for Push service!";break;case a.Status.SAME_NAME_USED_IN_SUPERCLASS:b="Same name is already used in a superclass.";break;case a.Status.PAYMENT_MAX_MODULE:b="Maximum number of used modules exceeded for this plan.";break;
case a.Status.PAYMENT_SYSTEM:b="Selected system use is not allowed for this plan.";break;case a.Status.PAYMENT_DOWNGRADE:b="Up/Downgrading plans is only allowed for super admins.";break;case a.Status.SAVE_REFERENECE_BEFORE_REFERENCING:b="Object you are trying to reference is not on the server. Please save it first.";break;case a.Status.PAYMENT_DB_SIZE:b="Used database size exceeds plan";break;case a.Status.ENDPOINT_PATH_NOT_ALLOWED:b="Endpoint not allowed for app; please add path to your app's config.";
break;case a.Status.PAYMENT_NO_CRON:b="Cronjobs are not allowed for this plan.";break;case a.Status.PAYMENT_MODULE_NOT_FREE:b="This module is not available for free plan.";break;case a.Status.NATIVEMODULE_DEACTIVATED:b="Native Module feature is not activated for this installation.";break;case a.Status.LICENSE_INVALID:b="Your license does not allow this action.";break;case a.Status.PAYMENT_NO_CUSTOMERROLES:b="Customer role usage is not available for free plan.";break;case a.Status.WHITELABEL:b="Only available for whitelabel installations.";
break;case a.Status.WHITELABEL_NOT:b="Not available for whitelabel installations.";break;case a.Status.MODULE_CONFIG_NO_DOT:b="No dot allowed in module config key.";break;case a.Status.PLAN_FALLBACK:b="Application cannot be activated without valid plan.";break;case a.Status.PLAN_INACTIVE:b="Plan is not selectable!";break;case a.Status.ENTERPRISE:b="Only available for enterprise installations.";break;case a.Status.ACCOUNT_UNACCEPTED_CONTRACTS:b="Account has unaccepted Contracts";break;case a.Status.DELETE_MANDATORY_DEFAULT_MODULE:b=
"It is not allowed to remove this default module";break;case a.Status.ID_EXISTS:b="ID exists!";break;case a.Status.NAME_RESERVED:b="Name is reserved!";break;case a.Status.CIRCULAR_DEPENDENCY:b="You can't set circular inheritance!";break;case a.Status.NAME_EXISTS:b="Name is already used!";break;case a.Status.EMAIL_EXISTS:b="E-mail is already used!";break;case a.Status.CUSTOMER_IN_ORG:b="Customer is already member of an organization";break;case a.Status.UNAUTHORIZED:b="Authorization failed!";break;
case a.Status.WRONG_APIKEY:b="API Key was not correct!";break;case a.Status.EVALANCHE_UNAUTH:b="Authorization failed! Maybe username/password was not set for evelanche configuration?";break;case a.Status.PW_CHANGE_W_TOKEN:b="Not authorized to change a user's password when authenticating with a token.";break;case a.Status.TOKEN_AUTH_ERROR:b="The token could not be authenticated";break;case a.Status.TOKEN_READ_ONLY:b="The token can only be used for read requests.";break;case a.Status.AUTHENTICATION_REJECTED:b=
"Authentication with username/password was rejected by third-party-system.";break;case a.Status.CRUD_ERROR:b="Internal error during CRUD operation";break;case a.Status.IMEXPORT_ERROR:b="Error during im/export!";break;case a.Status.COMPILE_ERROR:b="Classes could not be compiled!";break;case a.Status.REFERENCE_ERROR:b="Error in class reference!";break;case a.Status.PUSH_PAYLOAD_ERROR:b="Failed to create payload!";break;case a.Status.PUSH_SEND_ERROR:b="Failed to send message(s)!";break;case a.Status.PUSH_INIT_FAILED:b=
"Failed to initialize push service!";break;case a.Status.FACEBOOK_ERROR:b="An error occured while communicating with facebook!";break;case a.Status.FACEBOOK_OAUTH_ERROR:b="facebook throws oAuth error! Please show login dialog again";break;case a.Status.FACEBOOK_OAUTH_ERROR2:b="Received OAuth2 error from Facebook";break;case a.Status.MEMBER_NOT_FOUND:b="Can't find member with this id/username";break;case a.Status.WORDPRESS_FETCH_DATA_ERROR:b="Can't fetch data for wordpress blog";break;case a.Status.TUMBLR_OAUTH_ERROR:b=
"tumblr threw oAuth error! Please show login dialog again";break;case a.Status.TUMBLR_ERROR:b="Error communicating with tumblr!";break;case a.Status.EXECUTE_METHOD_ERROR_PRIMITIVE:b="Only primitive types are allowed";break;case a.Status.EXECUTE_METHOD_ERROR:b="Execute method failed";break;case a.Status.OAUTH_TOKEN_REQUEST_ERROR:b="An error occured during requesting an ApiOmat OAuth2 token";break;case a.Status.FINDING_RESOURCE_ERROR:b="An error occured while trying to find the resource";break;case a.Status.NATIVEMODULE_DEPLOY:b=
"Executing onDeploy failed";break;case a.Status.TOKEN_SEARCH_ERROR:b="An error occured while searching for tokens";break;case a.Status.MODULE_CONFIG_MISSING:b="Your module seems not to be configured properly";break;case a.Status.NATIVEMODULE_INIT:b="Could not initialize git repository";break;case a.Status.NATIVEMODULE_PULL:b="Could not pull git repository";break;case a.Status.NATIVEMODULE_PUSH:b="Could not push git repository";break;case a.Status.NO_DOGET_RETURN:b="The module's doGet didn't return a model";
break;case a.Status.CUSTOMER_TWO_ORGS:b="The customer was found in two organizations";break;case a.Status.NATIVEMODULE_HOOKS_NOT_FOUND:b="Annotated hook class not found";break;case a.Status.ANALYTICS_ERROR:b="The analytics instance couldn't process the request correctly";break;case a.Status.EMAIL_ERROR:b="Error during sending email";break;case a.Status.HREF_NOT_FOUND:b="Class has no HREF; please save it first!";break;case a.Status.WRONG_URI_SYNTAX:b="URI syntax is wrong";break;case a.Status.WRONG_CLIENT_PROTOCOL:b=
"Client protocol is wrong";break;case a.Status.IO_EXCEPTION:b="IOException was thrown";break;case a.Status.UNSUPPORTED_ENCODING:b="Encoding is not supported";break;case a.Status.INSTANTIATE_EXCEPTION:b="Error on class instantiation";break;case a.Status.IN_PERSISTING_PROCESS:b="Object is in persisting process. Please try again later";break;case a.Status.VERIFY_SOCIALMEDIA:b="Can't verify against social media provider";break;case a.Status.TOO_MANY_LOCALIDS:b="Can't create more localIDs. Please try again later";
break;case a.Status.MAX_CACHE_SIZE_REACHED:b="The maximum cache size is reached.";break;case a.Status.CANT_WRITE_IN_CACHE:b="Can't persist data to cache.";break;case a.Status.BAD_DATASTORE_CONFIG:b="For requesting a session token without a refresh token, the Datastore must be configured with a username and password";break;case a.Status.NO_TOKEN_RECEIVED:b="The response didn't contain a token";break;case a.Status.NO_NETWORK:b="No network connection available";break;case a.Status.ID_NOT_FOUND_OFFLINE:b=
"ID was not found in offline storage";break;case a.Status.ATTACHED_HREF_MISSING:b="HREF of attached image / file / reference is missing";break;case a.Status.REQUEST_TIMEOUT:b="The request timed out during connecting or reading the response";break;case a.Status.ASYNC_WAIT_ERROR:b="An error occured during waiting for an async task to finish";break;case a.Status.IN_DELETING_PROCESS:b="Object is in deleting process. Please try again later";break;case a.Status.SSO_REDIRECT:b="The request was redirected to an SSO Identity Provider";
break;case a.Status.MANUAL_CONCURRENT_WRITE_FAILED:b="Concurrent write to own concurrent data type failed";break;case a.Status.SAVE_FAILED:b="Load not executed because save already failed";break;case a.Status.MALICIOUS_MEMBER:b="Malicious use of member detected!";break;default:b="No reason found"}return b},getStatusForCode:function(c){var b=void 0;switch(c){case 701:b=a.Status.SCRIPT_ERROR;break;case 702:b=a.Status.APPLICATION_NOT_ACTIVE;break;case 703:b=a.Status.BAD_IMAGE;break;case 704:b=a.Status.BAD_ID;
break;case 705:b=a.Status.CONCURRENT_ACCESS;break;case 706:b=a.Status.APPLICATION_SANDBOX;break;case 707:b=a.Status.MODEL_NOT_DEPLOYED;break;case 709:b=a.Status.WRONG_REF_TYPE;break;case 710:b=a.Status.ATTRIBUTE_NOT_SET;break;case 711:b=a.Status.OPERATION_NOT_POSSIBLE;break;case 712:b=a.Status.APPLICATION_NAME_MISMATCH;break;case 713:b=a.Status.WRONG_AUTH_HEADER;break;case 714:b=a.Status.MODEL_STILL_USED;break;case 715:b=a.Status.COLLECTION_NOT_ALLOWED;break;case 716:b=a.Status.FB_NO_VALID_MEMBER;
break;case 717:b=a.Status.FB_NO_OAUTH_TOKEN;break;case 718:b=a.Status.FB_POST_ID_MISSING;break;case 719:b=a.Status.RESTORE_NO_DUMPS_FOUND;break;case 720:b=a.Status.TW_NO_VALID_MEMBER;break;case 721:b=a.Status.TW_NO_OAUTH_TOKEN;break;case 722:b=a.Status.IMEXPORT_WRONG_ENCODING;break;case 723:b=a.Status.IMEXPORT_WRONG_CONTENT;break;case 724:b=a.Status.PUSH_PAYLOAD_EXCEEDED;break;case 725:b=a.Status.PUSH_ERROR;break;case 726:b=a.Status.BAD_EMAIL;break;case 727:b=a.Status.BAD_PROMOTIONCODE_DISCOUNT;break;
case 728:b=a.Status.BAD_PROMOTIONCODE_CODE;break;case 729:b=a.Status.PLAN_PRICE;break;case 730:b=a.Status.PLAN_NO_SYSTEMS;break;case 731:b=a.Status.SCRIPT_TIME_ERROR;break;case 732:b=a.Status.INVALID_NAME;break;case 733:b=a.Status.ATTRIBUTE_IN_SUPERCLASS;break;case 734:b=a.Status.JSON_TYPE_ERROR;break;case 735:b=a.Status.TBLR_NO_VALID_MEMBER;break;case 736:b=a.Status.TBLR_NO_OAUTH_TOKEN;break;case 737:b=a.Status.TBLR_POST_ID_MISSING;break;case 738:b=a.Status.LOCATION_INVALID;break;case 739:b=a.Status.SCRIPT_EXCEPTION;
break;case 740:b=a.Status.BAD_ACCOUNTNAME;break;case 746:b=a.Status.BAD_IMAGE_ALPHA;break;case 747:b=a.Status.BAD_IMAGE_BGCOLOR;break;case 748:b=a.Status.BAD_IMAGE_FORMAT;break;case 708:b=a.Status.QUERY_ERROR;break;case 741:b=a.Status.BAD_TYPE_IN_QUERY;break;case 742:b=a.Status.UNKNOWN_CLASS_IN_QUERY;break;case 743:b=a.Status.WRONG_NUM_FORMAT_IN_QUERY;break;case 744:b=a.Status.QUERY_PARSE_ERROR;break;case 745:b=a.Status.UNKNOWN_ATTRIBUTE_IN_QUERY;break;case 749:b=a.Status.FOREIGNID_NOT_SET;break;
case 750:b=a.Status.CLASSES_MISSING;break;case 751:b=a.Status.INVALID_ATTRIBUTE_TYPE;break;case 752:b=a.Status.TOKEN_VALUE_EXISTS;break;case 753:b=a.Status.JSON_FORMAT_ERROR;break;case 754:b=a.Status.MODULE_DEPLOYMENT;break;case 755:b=a.Status.BAD_USERNAME;break;case 756:b=a.Status.CSV_ZIP_FORMAT;break;case 757:b=a.Status.VERIFICATION;break;case 758:b=a.Status.MODULE_STILL_USED;break;case 759:b=a.Status.CLASS_NOT_IN_MODULE;break;case 760:b=a.Status.ORDER_TRANSACTION_TIMESTAMP_OUTDATED;break;case 761:b=
a.Status.ORDER_TRANSACTION_ID_INVALID;break;case 762:b=a.Status.ORDER_TRANSACTION_SECRET_INVALID;break;case 763:b=a.Status.MANDATORY_FIELD;break;case 764:b=a.Status.INVALID_PASSWD_LENGTH;break;case 765:b=a.Status.BAD_PROMOTIONCODE_VALID;break;case 766:b=a.Status.BAD_CLASS_NAME_SAME_AS_MODULE;break;case 767:b=a.Status.NO_ORG_MEMBER;break;case 768:b=a.Status.MODULE_CLASS_NOT_CONTAINED;break;case 769:b=a.Status.BAD_GROUP_NAME;break;case 770:b=a.Status.INVISIBLE_CLASS;break;case 771:b=a.Status.MODULE_TYPE_NOT_ALLOWED;
break;case 801:b=a.Status.APPLICATION_NOT_FOUND;break;case 802:b=a.Status.CUSTOMER_NOT_FOUND;break;case 803:b=a.Status.ID_NOT_FOUND;break;case 804:b=a.Status.MODEL_NOT_FOUND;break;case 805:b=a.Status.MODULE_NOT_FOUND;break;case 807:b=a.Status.PLAN_NOT_FOUND;break;case 808:b=a.Status.PROMOCODE_NOT_FOUND;break;case 809:b=a.Status.DEMOAPP_NOT_FOUND;break;case 810:b=a.Status.ORGANIZATION_NOT_FOUND;break;case 811:b=a.Status.GROUP_NOT_FOUND;break;case 812:b=a.Status.ACCOUNT_NOT_FOUND;break;case 813:b=a.Status.DEFAULT_MODULE_NOT_FOUND;
break;case 820:b=a.Status.MODULE_USE_FORBIDDEN;break;case 821:b=a.Status.PUSH_ERROR_APIKEY;break;case 822:b=a.Status.PUSH_ERROR_CERTIFICATE;break;case 823:b=a.Status.SAME_NAME_USED_IN_SUPERCLASS;break;case 824:b=a.Status.PAYMENT_MAX_MODULE;break;case 825:b=a.Status.PAYMENT_SYSTEM;break;case 826:b=a.Status.PAYMENT_DOWNGRADE;break;case 827:b=a.Status.SAVE_REFERENECE_BEFORE_REFERENCING;break;case 828:b=a.Status.PAYMENT_DB_SIZE;break;case 829:b=a.Status.ENDPOINT_PATH_NOT_ALLOWED;break;case 1820:b=a.Status.PAYMENT_NO_CRON;
break;case 1821:b=a.Status.PAYMENT_MODULE_NOT_FREE;break;case 1822:b=a.Status.NATIVEMODULE_DEACTIVATED;break;case 1823:b=a.Status.LICENSE_INVALID;break;case 1824:b=a.Status.PAYMENT_NO_CUSTOMERROLES;break;case 1825:b=a.Status.WHITELABEL;break;case 1826:b=a.Status.WHITELABEL_NOT;break;case 1827:b=a.Status.MODULE_CONFIG_NO_DOT;break;case 1828:b=a.Status.PLAN_FALLBACK;break;case 1829:b=a.Status.PLAN_INACTIVE;break;case 1830:b=a.Status.ENTERPRISE;break;case 1831:b=a.Status.ACCOUNT_UNACCEPTED_CONTRACTS;
break;case 1832:b=a.Status.DELETE_MANDATORY_DEFAULT_MODULE;break;case 830:b=a.Status.ID_EXISTS;break;case 831:b=a.Status.NAME_RESERVED;break;case 832:b=a.Status.CIRCULAR_DEPENDENCY;break;case 833:b=a.Status.NAME_EXISTS;break;case 834:b=a.Status.EMAIL_EXISTS;break;case 835:b=a.Status.CUSTOMER_IN_ORG;break;case 840:b=a.Status.UNAUTHORIZED;break;case 841:b=a.Status.WRONG_APIKEY;break;case 842:b=a.Status.EVALANCHE_UNAUTH;break;case 843:b=a.Status.PW_CHANGE_W_TOKEN;break;case 844:b=a.Status.TOKEN_AUTH_ERROR;
break;case 845:b=a.Status.TOKEN_READ_ONLY;break;case 846:b=a.Status.AUTHENTICATION_REJECTED;break;case 901:b=a.Status.CRUD_ERROR;break;case 902:b=a.Status.IMEXPORT_ERROR;break;case 903:b=a.Status.COMPILE_ERROR;break;case 904:b=a.Status.REFERENCE_ERROR;break;case 905:b=a.Status.PUSH_PAYLOAD_ERROR;break;case 906:b=a.Status.PUSH_SEND_ERROR;break;case 907:b=a.Status.PUSH_INIT_FAILED;break;case 908:b=a.Status.FACEBOOK_ERROR;break;case 910:b=a.Status.FACEBOOK_OAUTH_ERROR;break;case 917:b=a.Status.FACEBOOK_OAUTH_ERROR2;
break;case 911:b=a.Status.MEMBER_NOT_FOUND;break;case 912:b=a.Status.WORDPRESS_FETCH_DATA_ERROR;break;case 913:b=a.Status.TUMBLR_OAUTH_ERROR;break;case 914:b=a.Status.TUMBLR_ERROR;break;case 915:b=a.Status.EXECUTE_METHOD_ERROR_PRIMITIVE;break;case 916:b=a.Status.EXECUTE_METHOD_ERROR;break;case 918:b=a.Status.OAUTH_TOKEN_REQUEST_ERROR;break;case 919:b=a.Status.FINDING_RESOURCE_ERROR;break;case 920:b=a.Status.NATIVEMODULE_DEPLOY;break;case 921:b=a.Status.TOKEN_SEARCH_ERROR;break;case 922:b=a.Status.MODULE_CONFIG_MISSING;
break;case 923:b=a.Status.NATIVEMODULE_INIT;break;case 924:b=a.Status.NATIVEMODULE_PULL;break;case 925:b=a.Status.NATIVEMODULE_PUSH;break;case 926:b=a.Status.NO_DOGET_RETURN;break;case 927:b=a.Status.CUSTOMER_TWO_ORGS;break;case 928:b=a.Status.NATIVEMODULE_HOOKS_NOT_FOUND;break;case 929:b=a.Status.ANALYTICS_ERROR;break;case 930:b=a.Status.EMAIL_ERROR;break;case 601:b=a.Status.HREF_NOT_FOUND;break;case 602:b=a.Status.WRONG_URI_SYNTAX;break;case 603:b=a.Status.WRONG_CLIENT_PROTOCOL;break;case 604:b=
a.Status.IO_EXCEPTION;break;case 605:b=a.Status.UNSUPPORTED_ENCODING;break;case 606:b=a.Status.INSTANTIATE_EXCEPTION;break;case 607:b=a.Status.IN_PERSISTING_PROCESS;break;case 608:b=a.Status.VERIFY_SOCIALMEDIA;break;case 609:b=a.Status.TOO_MANY_LOCALIDS;break;case 610:b=a.Status.MAX_CACHE_SIZE_REACHED;break;case 611:b=a.Status.CANT_WRITE_IN_CACHE;break;case 612:b=a.Status.BAD_DATASTORE_CONFIG;break;case 613:b=a.Status.NO_TOKEN_RECEIVED;break;case 614:b=a.Status.NO_NETWORK;break;case 615:b=a.Status.ID_NOT_FOUND_OFFLINE;
break;case 616:b=a.Status.ATTACHED_HREF_MISSING;break;case 617:b=a.Status.REQUEST_TIMEOUT;break;case 618:b=a.Status.ASYNC_WAIT_ERROR;break;case 619:b=a.Status.IN_DELETING_PROCESS;break;case 620:b=a.Status.SSO_REDIRECT;break;case 621:b=a.Status.MANUAL_CONCURRENT_WRITE_FAILED;break;case 622:b=a.Status.SAVE_FAILED;break;case 950:b=a.Status.MALICIOUS_MEMBER}return b}}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.ApiomatRequestError={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.ApiomatRequestError=function(c,b,d){this.message=d||a.Status.getReasonPhrase(c);this.name="ApiomatRequestError";this.expectedCodes=b;this.statusCode=c;this.extraInformations={};this.getStatusObj=function(){return a.Status.getStatusForCode(this.statusCode)};this.setExtraInformations=function(a){this.extraInformations=a};this.getExtraInformations=function(){return this.extraInformations}};a.ApiomatRequestError.prototype=Error();a.ApiomatRequestError.prototype.constructor=a.ApiomatRequestError})("undefined"===
typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMFileHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMFileHandler=function(){var a={},b=void 0;if("undefined"!==typeof window&&window.File&&window.FileReader&&window.FileList&&window.Blob){var d=function(a){console.log(a.target.error.code)},e=function(a){b=a},f=window.PERSISTENT;!f&&"undefined"!==typeof LocalFileSystem&&(f=LocalFileSystem.PERSISTENT);f&&"undefined"!==typeof window&&window.requestFileSystem&&window.requestFileSystem(f,0,e,d)}this.getAppDirectory=function(a,c){"undefined"!==typeof b?b.root.getDirectory("apiomatpersists",
{create:!0},function(b){a&&a(b)},function(a){console.error("Can't get directory handle!!");c&&c(a)}):a&&a(void 0)};this.getFileHandler=function(a,b,c,f){this.getAppDirectory(function(f){"undefined"!==typeof f?f.getFile(a,{},function(a){b&&b(a)},c):c()},c)};this.getSizeOfAppDir=function(a,c){if("undefined"!==typeof b){var f=this,e=function(a,b,g,d,k,h){g>=a.length?k(d):f.getFileHandler(b,function(b){b.file(function(b){d+=b.size;b=void 0;"undefined"!==typeof a[++g]&&(b=a[g].name);e(a,b,g,d,k,h)},h)},
function(b){b.code!==FileError.NOT_FOUND_ERR&&c?h(b):("undefined"!==typeof a[++g]&&(nextName=a[g].name),e(a,_nextName,g,d,k,h))})},d=function(b){void 0!==typeof b&&0<b.length?e(b,b[0].name,0,0,function(b){a&&a(b)},c):a&&a(0)};this.getAppDirectory(function(a){a.createReader().readEntries(d,c)},c)}else a&&a(0)};this.createFileName=function(a){return a+"_"+(new Date).getTime()};this.removeFile=function(f,e,d){"undefined"!==typeof b?this.getFileHandler(f,function(a){a.remove(function(){e&&e()},d)},function(a){a.code!==
FileError.NOT_FOUND_ERR&&d?d(a):e&&e()}):(delete a[f],e&&e())};this.readFile=function(f,e,d){"undefined"!==typeof b?this.getFileHandler(f,function(a){a.file(function(a){var b=new FileReader;b.onloadend=function(a){e&&e(a.target.result)};b.readAsText(a)})},function(a){a.code!==FileError.NOT_FOUND_ERR&&d?d(a):e&&e(void 0)}):e&&e(a[f])};this.writeFile=function(f,e,d,n){"undefined"!==typeof b?this.getFileHandler(f,function(a){a.createWriter(function(a){a.onwriteend=function(a){d&&d()};a.write(e)},n)},
n,{create:!0,exclusive:!1}):(a[f]=e,d&&d())}};a.AOMFileHandler.HREFMAP_FILENAME="hrefMap";a.AOMFileHandler.USEDLOCALIDS_FILENAME="usedLocalIDs";a.AOMFileHandler.TASKLIST_FILENAME="taskList";a.AOMFileHandler.prototype={}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMHelper={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMHelper=function(){return{isTitaniumApp:function(){return"object"===typeof Ti||"object"===typeof Titanium},isSafari:function(){return"object"===typeof navigator&&"undefined"!=typeof navigator.userAgent&&0>=navigator.userAgent.indexOf("Chrom")&&-1<navigator.userAgent.indexOf("Safari")||!1},isNodeJS:function(){return!1===this.isTitaniumApp()&&"undefined"!==typeof module&&module.exports},sendEvent:function(a,b){var d=void 0;this.isTitaniumApp()?Ti.App.fireEvent(a,b||{}):("undefined"!==
typeof CustomEvent&&!(9<=this.detectIE())?d=new CustomEvent(a,b||{}):(d=document.createEvent("Event"),d.initEvent(a,!0,!0),d.customData=b||{}),window.dispatchEvent(d))},isInteger:function(a){return 0===a%1},addEventListener:function(c,b){a.AOMHelper.isTitaniumApp()?Ti.App.addEventListener(c,b):window.addEventListener(c,b)},detectIE:function(){if(!1==this.isTitaniumApp()&&"undefined"!=typeof navigator&&"undefined"!=typeof navigator.userAgent&&null!=navigator.userAgent){var a=navigator.userAgent,b=
a.indexOf("MSIE ");if(0<b)return parseInt(a.substring(b+5,a.indexOf(".",b)),10);if(0<a.indexOf("Trident/"))return b=a.indexOf("rv:"),parseInt(a.substring(b+3,a.indexOf(".",b)),10);b=a.indexOf("Edge/");if(0<b)return parseInt(a.substring(b+5,a.indexOf(".",b)),10)}return!1}}}()})("undefined"===typeof exports?Apiomat:exports);
Array.prototype.filter||(Array.prototype.filter=function(a,c){if(!this)throw new TypeError;var b=Object(this);if("function"!==typeof a)throw new TypeError;var d=[],e;for(e in b)b.hasOwnProperty(e)&&a.call(c,b[e],e,b)&&d.push(b[e]);return d});String.prototype.endsWith||(String.prototype.endsWith=function(a){return-1!==this.indexOf(a,this.length-a.length)});
Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,c=!{toString:null}.propertyIsEnumerable("toString"),b="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),d=b.length;return function(e){if("object"!==typeof e&&("function"!==typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in e)a.call(e,g)&&f.push(g);if(c)for(g=0;g<d;g++)a.call(e,b[g])&&f.push(b[g]);return f}}());"undefined"!==typeof goog&&(Apiomat.MemoryStorage={});Array.prototype.contains=function(a){for(var c=this.length;c--;)if(this[c]===a)return!0;return!1};var _collectionStorage={},_objectStorage={},_useDeltaSync=!1;
(function(a){a.MemoryStorage=function(){function a(b){var c=[];for(i=0;i<b.length;i++)b[i]&&void 0!=b[i].id&&c.push(b[i].id);return c}function b(a){delete _objectStorage[a];for(var b in _collectionStorage)d(b,a)}function d(a,b){var c=_collectionStorage[a].indexOf(b);void 0!==c&&-1<c&&_collectionStorage[a].splice(c,1)}return{addOrUpdateCollection:function(b,f){if(f instanceof Array){if(_useDeltaSync)if(_collectionStorage.hasOwnProperty(b)){var d=_collectionStorage,q=_collectionStorage[b];for(i=0;i<
f.length;i++)void 0!=f[i].id&&!q.contains(f[i].id)&&q.push(f[i].id);d[b]=q}else _collectionStorage[b]=a(f);else _collectionStorage[b]=a(f);for(i=0;i<f.length;i++)this.addOrUpdateObject(f[i])}else this.addOrUpdateObject(f,b)},addOrUpdateObject:function(a,b){if(void 0!=a.id&&void 0!=b&&b.endsWith("/models/me")){if(_objectStorage.hasOwnProperty(b)&&_objectStorage[b].lastModifiedAt<=a.lastModifiedAt||!_objectStorage.hasOwnProperty(b))_objectStorage[b]=a}else if(void 0!=a.id){if(_objectStorage.hasOwnProperty(a.id)&&
_objectStorage[a.id].lastModifiedAt<=a.lastModifiedAt||!_objectStorage.hasOwnProperty(a.id))_objectStorage[a.id]=a}else-1<b.indexOf("images/")?_objectStorage[b.substring(b.lastIndexOf("images/")+7,b.lastIndexOf(".img"))]=a:-1<b.indexOf("files/")&&(_objectStorage[b.substring(b.lastIndexOf("files/")+6,b.lastIndexOf(".img"))]=a)},getCollection:function(a){return _collectionStorage[a]},getCollectionObjects:function(a){collection=this.getCollection(a);if(a.endsWith("/models/me"))return null==collection?
void 0:collection;if(!collection)return a=a.substring(a.lastIndexOf("/")+1,a.length),-1<a.indexOf(".img")&&(a=a.substring(0,a.lastIndexOf(".img"))),this.getObject(a);a=[];for(i=0;i<collection.length;i++)_objectStorage[collection[i]]&&a.push(_objectStorage[collection[i]]);return a},getObject:function(a){return _objectStorage[a]},removeCollection:function(a){delete _collectionStorage[a]},removeObjectByHref:function(a){var c=a.substring(0,a.lastIndexOf("/"));a=a.substring(a.lastIndexOf("/")+1,a.length);
var g=c.split("/"),q=!1;for(i=g.length-1;2<i;i--)if(null!=g[i].slice(0,1).match(/[0-9]/)){q=!0;break}c in _collectionStorage&&q?d(c,a):a in _objectStorage&&!q&&b(a)},removeObjectById:function(a){b(a)},removeObjectsOnDelta:function(a,b){if(_useDeltaSync&&a in _collectionStorage)for(i=0;i<b.length;i++)d(a,b[i])},getCollectionStorage:function(){return _collectionStorage},setUseDeltaSync:function(a){_useDeltaSync=a},getObjectStorage:function(){return _objectStorage},clearStorage:function(){this.clearCollections();
this.clearObjects()},clearCollections:function(){_collectionStorage={}},clearObjects:function(){_objectStorage={}}}}()})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMNetworkHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMNetworkHandler=function(){return{AOMNETWORKEVENT:"AomNetworkEvent",isChecking:!1,checkForConnection:function(){a.AOMNetworkHandler.isChecking=!0;!1===a.AOMNetworkHandler.isConnected()?setTimeout(a.AOMNetworkHandler.checkForConnection,150):(console.log("Connection is back..."),a.AOMNetworkHandler.isChecking=!1,a.AOMHelper.sendEvent(a.AOMNetworkHandler.AOMNETWORKEVENT,{isConnected:!0}))},isConnectedReact:function(){return Promise.resolve().then(function(){try{return NetInfo.isConnected.fetch()}catch(a){return!1}}).then(function(){})},
isConnected:function(){var c=!0,c=a.Datastore.getIsReact()?a.AOMNetworkHandler.isConnectedReact():a.AOMHelper.isTitaniumApp()?Titanium.Network.online:navigator.onLine;!0===a.forceOffline&&(c=!a.forceOffline);!1===c&&!1===a.AOMNetworkHandler.isChecking&&a.AOMNetworkHandler.checkForConnection();return c}}}()})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMFileHandlerTi={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMFileHandlerTi=function(){var a=function(){var a=Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory,"apiomatpersists");!1===a.exists()&&a.createDirectory();return a};this.getAppDirectory=function(b,d){var e=a();"undefined"===typeof e&&d?d():b&&b(e.nativePath)};this.getSizeOfAppDir=function(b,d){var e=a();"undefined"===typeof e&&d?d():b&&b(e.size)}};a.AOMHelper.isTitaniumApp()&&(a.AOMFileHandlerTi.prototype=new a.AOMFileHandler,a.AOMFileHandlerTi.prototype.constructor=a.AOMFileHandlerTi,
a.AOMFileHandlerTi.prototype.removeFile=function(a,b,d){var e=!1;this.getAppDirectory(function(f){f=Ti.Filesystem.getFile(f,a);f.exists()&&f.writeable&&(e=f.deleteFile());e?b&&b():d&&d()},d)},a.AOMFileHandlerTi.prototype.readFile=function(a,b,d){this.getAppDirectory(function(d){var f=void 0;d=Ti.Filesystem.getFile(d,a);d.exists()&&(f=d.read());f&&"undefined"!==typeof f?b&&b(f.text):b&&b(void 0)},d)},a.AOMFileHandlerTi.prototype.writeFile=function(a,b,d,e){this.getAppDirectory(function(f){Ti.Filesystem.getFile(f,
a).write(b)?d&&d():e&&e()},e)})})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMOfflineStorage={});
(function(a){a.AOMHelper.isTitaniumApp()&&(localStorage=Ti.App.Properties,localStorage.setItem=function(a,b){localStorage.setString(a,b)},localStorage.getItem=function(a){return localStorage.getString(a)},localStorage.removeItem=function(a){localStorage.removeProperty(a)},localStorage.clear=function(){var a=localStorage.listProperties();for(i=0;i<a.length;i++)localStorage.removeProperty(a[i]);return!0},localStorage.keys=localStorage.listProperties());a.AOMOfflineStorage=function(){function c(a){var b=
[];for(i=0;i<a.length;i++)a[i]&&void 0!=a[i].id&&b.push(a[i].id);return b}function b(a,b){var c=JSON.parse(localStorage.getItem(b));for(i=0;i<a.length;i++)if(void 0!=a[i].id){var d=!1;for(j=0;j<c.length;j++)if(c[j]===a[i].id){d=!0;break}d||c.push(a[i].id)}return null==c?void 0:c}function d(a,b){try{var c=JSON.parse(localStorage.getItem(a));if(c instanceof Array){var d=c.indexOf(b);void 0!==d&&-1<d&&(c.splice(d,1),localStorage.setItem(a,JSON.stringify(c)))}}catch(e){}finally{}}function e(b){localStorage.removeItem(b);
if(a.AOMHelper.isTitaniumApp()){var c=localStorage.listProperties(),e;for(e=0;e<c.length;e++)d(c[e],b);localStorage.listProperties()}else for(c in localStorage)d(c,b)}return{addOrUpdateCollection:function(a,d){if(d instanceof Array){_useDeltaSync?null===localStorage.getItem(a)?localStorage.setItem(a,JSON.stringify(c(d))):localStorage.setItem(a,JSON.stringify(b(d,a))):localStorage.setItem(a,JSON.stringify(c(d)));for(i=0;i<d.length;i++)this.addOrUpdateObject(d[i])}else this.addOrUpdateObject(d,a)},
addOrUpdateObject:function(a,b){void 0!=a.id&&void 0!=b&&b.endsWith("/models/me")?(null!==localStorage.getItem(b)&&JSON.parse(localStorage.getItem(b)).lastModifiedAt<=a.lastModifiedAt||null===localStorage.getItem(b))&&localStorage.setItem(b,JSON.stringify(a)):void 0!=a.id?(null!==localStorage.getItem(a.id)&&JSON.parse(localStorage.getItem(a.id)).lastModifiedAt<=a.lastModifiedAt||null===localStorage.getItem(a.id))&&localStorage.setItem(a.id,JSON.stringify(a)):-1<b.indexOf("images/")?localStorage.setItem(b.substring(b.lastIndexOf("images/")+
7,b.lastIndexOf(".img")),JSON.stringify(a)):-1<b.indexOf("files/")&&localStorage.setItem(b.substring(b.lastIndexOf("files/")+6,b.lastIndexOf(".img")),JSON.stringify(a))},getCollection:function(a){a=JSON.parse(localStorage.getItem(a));return null==a?void 0:a},getCollectionObjects:function(a){var b=this.getCollection(a);if(a.endsWith("/models/me"))return null==b?void 0:b;if(!b)return b=a.substring(a.lastIndexOf("/")+1,a.length),-1<b.indexOf(".img")&&(b=b.substring(0,b.lastIndexOf(".img"))),b=this.getObject(b),
null==b?void 0:b;a=[];for(i=0;i<b.length;i++)null!==localStorage.getItem(b[i])&&a.push(JSON.parse(localStorage.getItem(b[i])));return a},getObject:function(a){a=JSON.parse(localStorage.getItem(a));return null==a?void 0:a},removeCollection:function(a){localStorage.removeItem(a)},removeObjectByHref:function(a){var b=a.substring(0,a.lastIndexOf("/"));a=a.substring(a.lastIndexOf("/")+1,a.length);var c=b.split("/"),l=!1;for(i=c.length-1;2<i;i--)if(null!=c[i].slice(0,1).match(/[0-9]/)){l=!0;break}null!==
localStorage.getItem(b)&&l?d(b,a):null!==localStorage.getItem(a)&&!l&&e(a)},removeObjectById:function(a){e(a)},removeObjectsOnDelta:function(a,b){if(_useDeltaSync&&null!==localStorage.getItem(a))for(i=0;i<b.length;i++)d(a,b[i])},setUseDeltaSync:function(a){_useDeltaSync=a},getCollectionStorage:function(){return localStorage},clearStorage:function(){localStorage.clear()}}}()})("undefined"===typeof exports?Apiomat:exports);if("undefined"!==typeof goog)var base64={};
(function(a){if(!a.Base64){var c=function(a){for(var b={},c=0,d=a.length;c<d;c++)b[a.charAt(c)]=c;return b}("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),b=String.fromCharCode,d=function(a){if(2>a.length){var c=a.charCodeAt(0);return 128>c?a:2048>c?b(192|c>>>6)+b(128|c&63):b(224|c>>>12&15)+b(128|c>>>6&63)+b(128|c&63)}c=65536+1024*(a.charCodeAt(0)-55296)+(a.charCodeAt(1)-56320);return b(240|c>>>18&7)+b(128|c>>>12&63)+b(128|c>>>6&63)+b(128|c&63)},e=/[\uD800-\uDBFF][\uDC00-\uDFFFF]|[^\x00-\x7F]/g,
f=function(a){return a.replace(e,d)},g=function(a){var b=[0,2,1][a.length%3];a=a.charCodeAt(0)<<16|(1<a.length?a.charCodeAt(1):0)<<8|(2<a.length?a.charCodeAt(2):0);return["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>18),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>12&63),2<=b?"\x3d":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6&63),1<=b?"\x3d":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a&
63)].join("")},q=a.btoa||function(a){return a.replace(/[\s\S]{1,3}/g,g)},l=function(a,b){return!b?q(f(a)):q(f(a)).replace(/[+\/]/g,function(a){return"+"==a?"-":"_"}).replace(/=/g,"")},n=/[\u00c0-\u00df][\u0080-\u00bf]|[\u00e0-\u00ef][\u0080-\u00bf]{2}|[\u00f0-\u00f7][\u0080-\u00bf]{3}/g,k=function(a){switch(a.length){case 4:return a=((7&a.charCodeAt(0))<<18|(63&a.charCodeAt(1))<<12|(63&a.charCodeAt(2))<<6|63&a.charCodeAt(3))-65536,b((a>>>10)+55296)+b((a&1023)+56320);case 3:return b((15&a.charCodeAt(0))<<
12|(63&a.charCodeAt(1))<<6|63&a.charCodeAt(2));default:return b((31&a.charCodeAt(0))<<6|63&a.charCodeAt(1))}},C=function(a){return a.replace(n,k)},K=function(a){var d=a.length,e=d%4;a=(0<d?c[a.charAt(0)]<<18:0)|(1<d?c[a.charAt(1)]<<12:0)|(2<d?c[a.charAt(2)]<<6:0)|(3<d?c[a.charAt(3)]:0);a=[b(a>>>16),b(a>>>8&255),b(a&255)];a.length-=[0,0,2,1][e];return a.join("")},s=a.atob||function(a){return a.replace(/[\s\S]{1,4}/g,K)},t=function(a){return C(s(a))},D=function(a){return t(a.replace(/[-_]/g,function(a){return"-"==
a?"+":"/"}).replace(/[^A-Za-z0-9\+\/]/g,""))};a.Base64={VERSION:"2.1.2",atob:s,btoa:q,fromBase64:D,toBase64:l,utob:f,encode:l,encodeURI:function(a){return l(a,!0)},btou:C,decode:D};if("function"===typeof Object.defineProperty){var h=function(a){return{value:a,enumerable:!1,writable:!0,configurable:!0}};a.Base64.extendString=function(){Object.defineProperty(String.prototype,"fromBase64",h(function(){return D(this)}));Object.defineProperty(String.prototype,"toBase64",h(function(a){return l(this,a)}));
Object.defineProperty(String.prototype,"toBase64URI",h(function(){return l(this,!0)}))}}}})(this);"undefined"!==typeof goog&&(Apiomat.Datastore={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});function headerHook(a){return a}function responseHook(a){return a}function processOfflineHook(a){return a}
(function(a){a.AOMOfflineStrategy={NO_OFFLINE_HANDLING:0,USE_OFFLINE_CACHE:1};a.AOMCacheStrategy={NETWORK_ONLY:0,NETWORK_ELSE_CACHE:1,CACHE_ELSE_NETWORK:2,CACHE_THEN_NETWORK:3};a.AOMAuthType={GUEST:0,USERNAME_PASSWORD:1,OAUTH2_TOKEN:2};a.SSO_REDIRECT_URL="AOM_SSO_REDIRECT_URL";a.SSO_REDIRECT_DATA="AOM_SSO_REDIRECT_DATA";a.HEADER={ETAG:"Etag",LAST_MODIFIED:"Last-Modified",MODIFIED_SINCE:"If-Modified-Since",EXPIRES:"Expires",CACHE_CONTROL:"Cache-Control"};a.Datastore=function(){function c(b,c,d,P,e,
f,X){m=b;w=c;y=d;z=P;h=e;D=f;x=X;I="undefined"!==typeof x?a.AOMAuthType.OAUTH2_TOKEN:"undefined"!==typeof h&&"undefined"!==typeof D?a.AOMAuthType.USERNAME_PASSWORD:a.AOMAuthType.GUEST;Q=!0}function b(){return{getUsername:function(){return h},getPassword:function(){return D},getAuthType:function(){return I},setUseAsyncRequests:function(a){A=a},setUseDeltaSync:function(a){J=a},getUseDeltaSync:function(){return J},setOfflineUsageForClass:function(a,b){V[a]=b},getOfflineUsageForClass:function(a){return(a=
V[a])?a:!1},loadFromServer:function(b,c,d,P,e,h,m,g){var w=d&&b===d.getHref();f("GET",b,[200,304],!d?c:{onOk:function(b,F){b&&F&&304!==F.status?d.fromJson(b):F&&304===F.status||d.fromJson(b);a.Datastore.positiveCallback(c,F&&304==F.status?d:void 0,F)},onError:function(b,F){a.Datastore.negativeCallback(c,b,F)},onSecondOk:function(b,F){d.fromJson(b);a.Datastore.secondPositiveCallback(c,F)}},h,{isReload:w,data:e,withReferencedHrefs:P},m,g)},getOrCreateUser:function(b,c,d){var e=a.User.AOMBASEURL.substring(a.User.AOMBASEURL.lastIndexOf("/")+
1);b=m.substring(0,m.indexOf("yambas/rest")+11)+"/modules/facebook/spec/"+e+"/aomuser?facebookToken\x3d"+b;f("GET",b,[200],c,void 0,void 0,d)},loginFacebook:function(b,c,d){a.Datastore.getInstance().getOrCreateUser(b,c,d)},setCheckObjectState:function(a){Q=a},getCheckObjectState:function(){return Q},loadResource:function(a,b,c){f("GET",a,[200,206],b,void 0,{isByteData:!0},c)},loadListFromServerWithClass:function(a,b,c,d,e){f("GET",k(a),[200,304],c,a,{data:b,withReferencedHrefs:d},!0,e)},postOnServer:function(a,
b,c,d){c||(c=n(a));f("POST",c,[200,201],b,void 0,{data:a.toJson()},void 0,d)},updateOnServer:function(a,b,c){var d=a.getHref();a=a.toJson();f("PUT",d,[200,204],b,void 0,{data:a},void 0,c)},updateOnServerWithJSON:function(a,b,c,d){f("PUT",a,[200,204],c,void 0,{data:b},void 0,d)},deleteOnServer:function(a,b,c){d(a,void 0,b,c)},deleteModelOnServer:function(a,b,c){d(void 0,a,b,c)},postStaticDataOnServer:function(a,b,c,d){b=C(b);this.postStaticDataOnServerWithHref(a,b,c,d)},postStaticDataOnServerWithHref:function(a,
b,c,d){f("POST",b,[201],c,void 0,{isByteData:!0,data:a},d)},shouldSendOffline:function(b){return u!==a.AOMCacheStrategy.NETWORK_ONLY&&void 0!=this.getOfflineHandler()&&!1===this.getOfflineHandler().isConnected()},getOfflineHandler:function(){return r},getOfflineStrategy:function(){return p},syncCollection:function(a,b,c){var d=[],e=[],f=!1,h,m;if(c)for(h=0;h<a.length;h++){f=!1;for(m=0;m<c.length;m++)a[h].getID()==c[m]&&(f=!0);f||d.push(a[h])}else d=a;for(a=0;a<b.length;a++){f=!1;for(c=0;c<d.length;c++)d[c].getID()===
b[a].getID()&&(d[c]=b[a],f=!0);f||e.push(b[a])}return d.concat(e)},sendOffline:function(b,c,d,e,f){!c&&d instanceof a.AbstractClientDataModel?c=n(d):c||(c=C(e));this.getOfflineHandler().addTask(b,c,d,e,function(c){"POST"===b&&c?a.Datastore.positiveCallback(f,c):a.Datastore.positiveCallback(f)},function(c){"undefined"!==typeof f?("POST"===b&&(c=new a.ApiomatRequestError(a.Status.CRUD_ERROR,201,"Can't save offline")),a.Datastore.negativeCallback(f,c)):"undefined"!==typeof console&&console.error&&console.error("Can't send request to offline queue: "+
c)})},requestSessionToken:function(b,c,d,f){if(I!==a.AOMAuthType.USERNAME_PASSWORD)c=new a.ApiomatRequestError(a.Status.BAD_DATASTORE_CONFIG),"undefined"!==typeof b?a.Datastore.negativeCallback(b,c):"undefined"!==typeof console&&console.error&&console.error("Error occured: "+c);else{var L=m.substring(m.lastIndexOf("/")+1),L={grant_type:"aom_user",client_id:L,client_secret:w,scope:"read write",username:h,password:D,app:L,system:y};"undefined"!==typeof d&&"default"!==d&&(L.access_expiration=d);"undefined"!==
typeof f&&"default"!==f&&(L.refresh_expiration=f);e(L,b,c)}},requestSessionTokenWithRefreshToken:function(a,b,c,d,f){a={grant_type:"refresh_token",client_id:m.substring(m.lastIndexOf("/")+1),client_secret:w,refresh_token:a};"undefined"!==typeof d&&"default"!==d&&(a.access_expiration=d);"undefined"!==typeof f&&"default"!==f&&(a.refresh_expiration=f);e(a,b,c)},loadCountFromServer:function(b,c,d,e,h){var m=void 0,m="string"===typeof b&&"undefined"!==typeof c?b+"/"+c:k(b);f("GET",m+"/count",[200],{onOk:function(b){a.Datastore.positiveCallback(e,
Number(b))},onError:function(b){typeof e&&a.Datastore.negativeCallback(e,b)}},void 0,{data:d,returnpost:!0},h)},setIdPHosts:function(a){N=a},getIdPHosts:function(){return N},deleteCollectionFromStorage:function(b,c,d,e){var f=!1;try{var h=c.prototype.getModuleName(),g=c.prototype.getSimpleName();c=m+"/models/"+h+"/"+g;b&&(c+="?withReferencedHrefs\x3d"+b);d&&(c=b?c+"\x26":c+"?",c+="q\x3d"+d);collectionHref=c;headerHook(collectionHref);a.MemoryStorage.removeCollection(collectionHref);a.AOMOfflineStorage.removeCollection(collectionHref);
a.Datastore.positiveCallback(e)}catch(w){H?Ti.API.log("Error occured: "+w):f=!0}finally{f&&(b=new a.ApiomatRequestError(a.status.MODEL_NOT_FOUND),"undefined"!==typeof e?a.Datastore.negativeCallback(e,b):"undefined"!==typeof console&&console.error&&console.error("Error occured: "+b))}},deleteObjectFromStorage:function(a,b){s(b).removeObjectById(a)},removeCollectionFromStorage:function(a,b){s(b).removeObjectByHref(a)},createHrefFromClass:function(a){return k(a)}}}function d(b,c,d,e){b?f("DELETE",b,
[204],d,void 0,void 0,e):c&&c.getHref()?f("DELETE",c.getHref(),[204],d,void 0,void 0,e):(b=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND),d?a.Datastore.negativeCallback(d,b):console&&console.error&&console.error("Error occured: "+b))}function e(b,c,d){var e=m.substring(0,m.indexOf("yambas")+6)+"/oauth/token",h="",g;for(g in b)""!==h&&(h+="\x26"),h+=g+"\x3d"+b[g];f("POST",e,[200],{onOk:function(b){var d={};b=JSON.parse(b)||{};d.sessionToken=b.access_token;d.refreshToken=b.refresh_token;var e=b.expires_in||
0;d.expirationDate=(new Date).getTime()+1E3*e;d.module=b.aom_module;d.model=b.aom_model;a.Datastore.positiveCallback(c,d)},onError:function(b){b=new a.ApiomatRequestError(b.statusCode,200,"Requesting the session token failed");"undefined"!==typeof c?a.Datastore.negativeCallback(c,b):console&&console.error&&console.error("Error occured: "+b)}},void 0,{data:h,returnpost:!0,headerDetails:{authHeader:!1,contentType:"application/x-www-form-urlencoded"}},d)}function f(b,c,d,e,f,h,w,y){h=h||{};var p=h.data||
void 0,z=h.withReferencedHrefs||void 0,r=h.isByteData||!1,s=h.returnpost||!1,k=h.headerDetails||{},n=h.isReload,B;H?(B=Ti.Network.createHTTPClient({onload:function(a){g(this,d,e,b,f,s,c,y)},onerror:function(b){var c=b.error||"";if(-1<c.indexOf("connection failure"))b=new a.ApiomatRequestError(a.Status.NO_NETWORK,d,c);else{if(-1<d.indexOf(this.status))throw b;b=new a.ApiomatRequestError(this.status,d,this.responseText)}"undefined"!==typeof e?a.Datastore.negativeCallback(e,b):Ti.API.error("Received HTTP error: "+
b)}}),B.overrideMimeType=function(){}):B="object"===typeof window&&window.XMLHttpRequest?new XMLHttpRequest:R?new exports.XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");"GET"===b&&p&&(c+="?q\x3d"+encodeURIComponent(p));if(!1==H&&!1==R&&!1==S){var M=!1,M=O;"GET"===b&&(!1!=M&&10>=M)&&(c=p?c+"\x26":c+"?",c+="dIE\x3d"+(new Date).getTime())}"GET"===b&&("undefined"!=typeof z&&!0==z)&&(c=p||!1!=M&&10>=M?c+"\x26":c+"?",c+="withReferencedHrefs\x3d"+z);c="http"===c.substring(0,4)?c:"/apps"===c.substring(0,
5)?m.substring(0,m.indexOf("/apps"))+c:m+"/"+c;a.AOMNetworkHandler.isConnected()&&u!==a.AOMCacheStrategy.CACHE_ELSE_NETWORK&&u!==a.AOMCacheStrategy.CACHE_THEN_NETWORK||"GET"!==b?(B.open(b,c,A),l(c,b,B,r,k,n,w,y),r&&"GET"===b&&B.overrideMimeType("text/plain; charset\x3dx-user-defined"),!1==H&&(B.onreadystatechange=function(){4==B.readyState&&g(B,d,e,b,f,s,c,y)}),("POST"===b||"PUT"===b)&&"undefined"!==typeof p?h&&h.isByteData?(h=p,!1===H&&(p=new Uint8Array(p),h="ArrayBufferView"in window?p:p.buffer),
B.send(h)):B.send(p):B.send()):u!==a.AOMCacheStrategy.NETWORK_ONLY?q(e,f,c,B,b,r,k,w,d,s,y):(p=new a.ApiomatRequestError(a.Status.NO_NETWORK,d),"undefined"!==typeof e?a.Datastore.negativeCallback(e,p):"undefined"!==typeof console&&console.error&&console.error("Error occured: "+p))}function g(b,c,d,e,f,h,m,g){var w=!1;responseHook(b);processOfflineHook(!1);try{var y=b.responseURL,p=b.getResponseHeader("Content-Type"),l=void 0;if(p&&-1<p.indexOf("text/html")){for(var p=void 0,z=b.responseText,r=/<form.+method.?=.?"POST".+?action=.?"(.*?)".*?>/g;match=
r.exec(z);)for(var q in N)if(-1<match[1].indexOf(N[q])){p=match[1];break}l=p;if("undefined"!==typeof l){var A=new a.ApiomatRequestError(a.Status.SSO_REDIRECT,c,null);e={};e[a.SSO_REDIRECT_URL]=l;e[a.SSO_REDIRECT_DATA]=b.responseText;A.setExtraInformations(e);if("undefined"!==typeof d&&d.onError)d.onError(A,{status:b.status});return}}if(-1<c.indexOf(b.status)){if(d&&d.hasOwnProperty("onOk")){if((S||O)&&"GET"===e)T[m]=b.getResponseHeader("Last-Modified"),O&&(U[m]=b.getResponseHeader(a.HEADER.ETAG));
var v=b.responseText;if("GET"===e&&0<v.length)try{if(u!==a.AOMCacheStrategy.NETWORK_ONLY){var k=s(g);k.addOrUpdateCollection(y?y:m,JSON.parse(v));if(J){var n={deletedItems:JSON.parse(b.getResponseHeader("X-apiomat-delta-deleted"))};n.deletedItems&&0<n.deletedItems.length&&(k=s(g),k.removeObjectsOnDelta(m,n.deletedItems))}}}catch(C){var l="",A=[],E,t;for(E=0;E<v.length;E++)A.push(v[E].charCodeAt(0)&255);for(t=0;t<A.length;t++)l+=String.fromCharCode(A[t]);k=s(g);k.addOrUpdateCollection(y?y:m,l);if(J){try{n=
{deletedItems:JSON.parse(b.getResponseHeader("X-apiomat-delta-deleted"))}}catch(D){n={deletedItems:void 0}}n.deletedItems&&0<n.deletedItems.length&&(k=s(g),k.removeObjectsOnDelta(m,n.deletedItems))}}"DELETE"===e&&u!==a.AOMCacheStrategy.NETWORK_ONLY&&s(g).removeObjectByHref(m);v=b.responseText;if("GET"===e&&"undefined"!==typeof f){var G=[],G=J&&u!==a.AOMCacheStrategy.NETWORK_ONLY||u===a.AOMCacheStrategy.NETWORK_ELSE_CACHE&&304===b.status?s(g).getCollectionObjects(m):JSON.parse(v);if(G instanceof Array){v=
[];for(E=0;E<G.length;E++){var x=new f;x.fromJson(G[E]);v.push(x)}}else v=new f,v.fromJson(G)}f=void 0;"POST"===e&&!1===h&&(f=b.getResponseHeader("Location"));"GET"===e&&u===a.AOMCacheStrategy.CACHE_THEN_NETWORK&&d.hasOwnProperty("onSecondOk")?a.Datastore.secondPositiveCallback(d,v):a.Datastore.positiveCallback(d,"GET"===e||h?v:f||void 0,n,{status:b.status})}}else if("GET"===e&&u===a.AOMCacheStrategy.NETWORK_ELSE_CACHE){if("undefined"!==typeof f)if(G=[],G=s(g).getCollectionObjects(m),G instanceof
Array){v=[];for(E=0;E<G.length;E++)x=new f,x.fromJson(G[E]),v.push(x)}else v=new f,v.fromJson(G);a.Datastore.positiveCallback(d,v)}else w=!0}catch(I){H&&Ti.API.log("Error occured: "+I);if(b&&-1<c.indexOf(b.status))throw I;w=!0}finally{w&&(console.log("Status: "+b.status),A=new a.ApiomatRequestError(b.status,c,b.responseText),"undefined"!==typeof d?a.Datastore.negativeCallback(d,A,{status:b.status}):"undefined"!==typeof console&&console.error&&console.error("Error occured: "+A))}}function q(b,c,d,
e,f,h,m,w,y,p,z){processOfflineHook(!0);var r=!1,q;try{if(b&&b.hasOwnProperty("onOk")){var k,n=s(z).getCollectionObjects(d);if(n){if(n instanceof Array){k=[];var t;for(t=0;t<n.length;t++){var v=new c;v.fromJson(n[t]);k.push(v)}}else c?(k=new c,k.fromJson(n)):k=n instanceof Object?JSON.stringify(n):n;a.Datastore.positiveCallback(b,k);u===a.AOMCacheStrategy.CACHE_THEN_NETWORK&&(e.open(f,d,A),l(d,f,e,h,m,w,z),h&&"GET"===f&&e.overrideMimeType("text/plain; charset\x3dx-user-defined"),!1==H&&(e.onreadystatechange=
function(){4==e.readyState&&g(e,y,b,f,c,p,d,z)}),e.send())}else a.AOMNetworkHandler.isConnected()&&u===a.AOMCacheStrategy.CACHE_ELSE_NETWORK||u===a.AOMCacheStrategy.CACHE_THEN_NETWORK?(u===a.AOMCacheStrategy.CACHE_THEN_NETWORK&&a.Datastore.positiveCallback(b,[]),e.open(f,d,A),l(d,f,e,h,m,w,z),h&&"GET"===f&&e.overrideMimeType("text/plain; charset\x3dx-user-defined"),!1==H&&(e.onreadystatechange=function(){4==e.readyState&&g(e,y,b,f,c,p,d,z)}),e.send()):(r=!0,q=new a.ApiomatRequestError(a.Status.ID_NOT_FOUND_OFFLINE,
201,"No data found offline"))}}catch(x){H&&Ti.API.log("Error occured: "+x),r=!0}finally{r&&(q||(q=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND)),"undefined"!==typeof b?a.Datastore.negativeCallback(b,q):"undefined"!==typeof console&&console.error&&console.error("Error occured: "+q))}}function l(b,c,d,e,f,m,g,p){d.setRequestHeader("X-apiomat-system",y);d.setRequestHeader("X-apiomat-apikey",w);f.contentType?d.setRequestHeader("Content-Type",f.contentType):"undefined"!==typeof e&&e?d.setRequestHeader("Content-Type",
"application/octet-stream"):(d.setRequestHeader("Content-Type","application/json"),d.setRequestHeader("Accept","application/json"));d.setRequestHeader("X-apiomat-fullupdate","true");if(!(f.hasOwnProperty("authHeader")&&!1==f.authHeader))if(I===a.AOMAuthType.USERNAME_PASSWORD){e=h+":"+D;if(R)try{e=(new (require("buffer").Buffer)(e)).toString("base64")}catch(l){e=Base64.Base64.encode(e)}else try{e=Base64.encode(e)}catch(n){e=Base64.Base64.encode(e)}d.setRequestHeader("Authorization","Basic "+e)}else I===
a.AOMAuthType.OAUTH2_TOKEN&&d.setRequestHeader("Authorization","Bearer "+x);d.setRequestHeader("X-apiomat-sdkVersion",z);(S||H)&&"GET"===c?d.setRequestHeader("If-Modified-Since","01.01.1970 00:00:00:00 CEST"):O&&"GET"===c&&(d.setRequestHeader(a.HEADER.MODIFIED_SINCE,"Wed, 02 Mar 1970 12:00:00 GMT"),d.setRequestHeader(a.HEADER.EXPIRES,-1),d.setRequestHeader(a.HEADER.CACHE_CONTROL,"must-revalidate, private"),m&&(U[b]&&d.setRequestHeader("If-None-Match",U[b]),null!==T[b]&&d.setRequestHeader(a.HEADER.LAST_MODIFIED,
T[b])));if(g&&"GET"==c&&J&&u!==a.AOMCacheStrategy.NETWORK_ONLY)if(c=s(p),b=c.getCollection(b)){m=[];for(i=0;i<b.length;i++)(g=c.getObject(b[i]))&&m.push(g);d.setRequestHeader("X-apiomat-delta",K(m));headerHook(m)}else d.setRequestHeader("X-apiomat-delta","{}")}function n(a){var b=m,b=b+"/models/"+a.getModuleName(),b=b+"/";return b+=a.getSimpleName()}function k(a){var b=m,b=b+"/models/"+a.prototype.getModuleName.call(),b=b+"/";return b+=a.prototype.getSimpleName.call()}function C(a){var b=m,b=b+"/data/"+
(a?"images":"files");return b+="/"}function K(a){var b="{";for(i=0;i<a.length;i++)0<i&&(b=b.concat(", ")),b=b.concat("'"+a[i].id+"' : '"+a[i].lastModifiedAt+"'");return b=b.concat("}")}function s(b){if(b&&!r)if(u)!r&&u!==a.AOMCacheStrategy.NETWORK_ONLY&&(r=new a.AOMOfflineHandler),"undefined"!==typeof r&&r.init(void 0,void 0);else throw"No cachingStrategy is set. Please set the strategy in the Datastore with setCachingStrategy(cacheStrategy, callback)";return b?a.AOMOfflineStorage:a.MemoryStorage}
var t,D,h,m,w,y,z,A=!0,p=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING,r=void 0,I=a.AOMAuthType.GUEST,x,Q=void 0,N=[],J=!1,V={},u=a.AOMCacheStrategy.NETWORK_ELSE_CACHE,W=!1,S=a.AOMHelper.isSafari(),H=a.AOMHelper.isTitaniumApp(),R=a.AOMHelper.isNodeJS(),O=a.AOMHelper.detectIE(),T=[],U=[];a.MemoryStorage.clearCollections();a.MemoryStorage.clearObjects();return{getInstance:function(){t||(t=b());return t},isInstantiated:function(){return"undefined"!==typeof t&&t},positiveCallback:function(a,b,c){a||console.log("Positive callback: callback not defined");
var d;if("undefined"!==typeof a&&a!={})for(d in a){var e="function"==typeof a[d]&&"onok"==d.toString().toLowerCase()?d.toString():void 0;if("undefined"!=typeof e){if(b&&"undefined"!=typeof b&&null!==b)a[e](b,c);else a[e](void 0,c);break}}},secondPositiveCallback:function(a,b,c){a||console.log("Second positive callback: callback not defined");var d;if("undefined"!==typeof a&&a!={})for(d in a){var e="function"==typeof a[d]&&"onsecondok"==d.toString().toLowerCase()?d.toString():void 0;if("undefined"!=
typeof e){if(b&&"undefined"!=typeof b)a[e](b,c);else a[e]();break}}},negativeCallback:function(a,b,c){var d;if("undefined"!==typeof a&&a!={})for(d in a)if(c="function"==typeof a[d]&&"onerror"==d.toString().toLowerCase()?d.toString():void 0,"undefined"!=typeof c){if(b&&"undefined"!=typeof b)a[c](b);else a[c]();break}},configure:function(a){this.configureWithCredentials(a)},configureWithCredentials:function(b){c(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS,a.User.AOMSDKVERSION,b.getUserName(),b.getPassword())},
configureAsGuest:function(a,b,d,e){c(a,b,d,e)},configureWithUserSessionToken:function(a){this.configureWithSessionToken(a.getSessionToken())},configureWithSessionToken:function(b){c(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS,a.User.AOMSDKVERSION,void 0,void 0,b)},configurePlain:function(a,b,c,d){this.configureAsGuest(a,b,c,d)},setOfflineStrategy:function(b,c){p=b;!r&&p!=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING&&(r=new a.AOMOfflineHandler);"undefined"!==typeof r&&("undefined"!==typeof c?r.init(c.onOk||
void 0,c.onError||void 0):r.init(void 0,void 0))},getCachingStrategy:function(){return u},setCachingStrategy:function(b,c){if(!this)throw"The datastore hasn't been configured yet - call Datastore.configure(...) before sending requests.";u=b;!r&&u!==a.AOMCacheStrategy.NETWORK_ONLY&&(r=new a.AOMOfflineHandler);"undefined"!==typeof r&&("undefined"!==typeof c?r.init(c.onOk||void 0,c.onError||void 0):r.init(void 0,void 0))},setUseDeltaSync:function(b){console.log(67);J=b;a.MemoryStorage.setUseDeltaSync(b);
a.AOMOfflineStorage.setUseDeltaSync(b)},setIsReact:function(a){W=a},getIsReact:function(){return W}}}()})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AbstractClientDataModel={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.ObjectState={TRANSIENT:"TRANSIENT",DELETING:"DELETING",DELETED:"DELETED",PERSISTING:"PERSISTING",PERSISTED:"PERSISTED",LOCAL_PERSISTED:"LOCAL_PERSISTED",LOCAL_DELETED:"LOCAL_DELETED"};a.AbstractClientDataModel=function(){this.data={};this.toJson=function(){this.getHref()&&(this.data.id=this.getID());this.data["@type"]=this.getType();var a=JSON.stringify(this.data);delete this.data.id;return a};this.fromJson=function(c){if("object"===typeof c)for(var b in c)this.data[b]=c[b];else this.data=
JSON.parse(c);this.setCurrentState(a.ObjectState.PERSISTED);return this};this.getCurrentState=function(){return this.currentState};this.setCurrentState=function(a){this.currentState=a}};a.AbstractClientDataModel.prototype={getModuleName:function(){throw new a.ApiomatRequestError(void 0,void 0,"Must be implemented by child");},getSimpleName:function(){throw new a.ApiomatRequestError(void 0,void 0,"Must be implemented by child");},getType:function(){return this.getModuleName()+"$"+this.getSimpleName()},
getHref:function(){return this.data.href},getRefModelHrefs:function(){return this.data.referencedHrefs},getRefModelHrefsForName:function(a){var b=this.getRefModelHrefs();return b.hasOwnProperty(a)||a in b?b[a]:null},getAllowedRolesGrant:function(){return this.data.allowedRolesGrant},setAllowedRolesGrant:function(a){this.data.allowedRolesGrant=a},getAllowedRolesWrite:function(){return this.data.allowedRolesWrite},setAllowedRolesWrite:function(a){this.data.allowedRolesWrite=a},getAllowedRolesRead:function(){return this.data.allowedRolesRead},
setAllowedRolesRead:function(a){this.data.allowedRolesRead=a},getRstrictResourceAccess:function(){return this.data.restrictResourceAccess},setRestrictResourceAccess:function(a){this.data.restrictResourceAccess=a},getForeignId:function(){return this.data.foreignId},setForeignId:function(a){this.data.foreignId=a},getCreatedAt:function(){return new Date(this.data.createdAt)},getLastModifiedAt:function(){return new Date(this.data.lastModifiedAt)},getAppName:function(){return this.data.applicationName},
load:function(a,b){this.loadWithHref(void 0,a,b)},loadAndRefHref:function(a,b){this.loadWithHrefAndRefHref(void 0,a,b)},loadWithHref:function(c,b,d){this.isIllegalState()?(c="Object is in persisting or deleting process. Please try again later",this.getCurrentState()==a.ObjectState.PERSISTING?c=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,"Object is in persisting process. Please try again later"):this.getCurrentState()==a.ObjectState.DELETING&&(c=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,
201,"Object is in deleting process. Please try again later")),a.Datastore.negativeCallback(b,c)):a.Datastore.getInstance().loadFromServer(c||this.getHref(),b,this,!1,void 0,void 0,void 0,d)},loadWithHrefAndRefHref:function(c,b,d){this.isIllegalState()?(c="Object is in persisting or deleting process. Please try again later",this.getCurrentState()==a.ObjectState.PERSISTING?c=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,"Object is in persisting process. Please try again later"):this.getCurrentState()==
a.ObjectState.DELETING&&(c=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,201,"Object is in deleting process. Please try again later")),a.Datastore.negativeCallback(b,c)):a.Datastore.getInstance().loadFromServer(c||this.getHref(),b,this,!0,void 0,void 0,!1,d)},save:function(c,b,d){if(this.isIllegalState()){var e="Object is in persisting or deleting process. Please try again later";this.getCurrentState()==a.ObjectState.PERSISTING?e=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,
"Object is in persisting process. Please try again later"):this.getCurrentState()==a.ObjectState.DELETING&&(e=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,201,"Object is in deleting process. Please try again later"));a.Datastore.negativeCallback(c,e)}else this.setCurrentState(a.ObjectState.PERSISTING),b="undefined"!==typeof b&&b.constructor===Boolean?b:!0,e={onOk:function(e){!this.parent.getHref()&&e&&(this.parent.data.href=e);this.parent.setOffline(this.wasLocalSave||!1);!this.wasLocalSave&&
b?(this.parent.setCurrentState(a.ObjectState.PERSISTED),this.parent.load({onOk:function(){a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,b)},onSecondOk:function(){a.Datastore.secondPositiveCallback(c)}},d)):(this.parent.setCurrentState(a.ObjectState.LOCAL_PERSISTED),a.Datastore.positiveCallback(c))},onError:function(b){this.parent.setCurrentState(a.ObjectState.TRANSIENT);a.Datastore.negativeCallback(c,b)},onSecondOk:function(){},parent:this},this.getHref()?a.Datastore.getInstance().shouldSendOffline("PUT")?
(e.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("PUT",this.getHref(),this,void 0,e)):a.Datastore.getInstance().updateOnServer(this,e,d):a.Datastore.getInstance().shouldSendOffline("POST")?(e.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("POST",void 0,this,void 0,e)):a.Datastore.getInstance().postOnServer(this,e,void 0,d)},deleteModel:function(c,b){if(this.isIllegalState()){var d="Object is in persisting or deleting process. Please try again later";this.getCurrentState()==a.ObjectState.PERSISTING?
d=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,"Object is in persisting process. Please try again later"):this.getCurrentState()==a.ObjectState.DELETING&&(d=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,201,"Object is in deleting process. Please try again later"));a.Datastore.negativeCallback(c,d)}else this.setCurrentState(a.ObjectState.DELETING),d={onOk:function(b){this.parent.setCurrentState(this.finishedState);"undefined"!=typeof b?a.Datastore.positiveCallback(c,b):a.Datastore.positiveCallback(c)},
onError:function(b){this.parent.setCurrentState(a.ObjectState.TRANSIENT);a.Datastore.negativeCallback(c,b)},parent:this},a.Datastore.getInstance().shouldSendOffline("DELETE")?(d.finishedState=a.ObjectState.LOCAL_DELETED,a.Datastore.getInstance().sendOffline("DELETE",this.getHref(),this,void 0,d)):(d.finishedState=a.ObjectState.DELETED,a.Datastore.getInstance().deleteModelOnServer(this,d,b))},isOffline:function(){return this.data.isOffline||!1},setOffline:function(a){this.data.isOffline=a},getID:function(){return this.getHref().substring(this.getHref().lastIndexOf("/")+
1)},getAllObjectStates:function(){return this.ObjectState},isIllegalState:function(){var c=!1;a.Datastore.getInstance().getCheckObjectState()&&(c=this.getCurrentState()==a.ObjectState.PERSISTING||this.getCurrentState()==a.ObjectState.DELETING);return c}}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMOfflineInfo={},Apiomat.AOMOfflineHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMOfflineInfo=function(a,b,d,e,f,g,q){this.httpMethod=a;this.fileKey=d;this.timestamp=e;this.url=b;this.clazz=e;this.localId=f;this.refName=g;this.isStaticData=q};a.AOMOfflineHandler=function(){a.AOMOfflineHandler.AOMTASKEVENT="AomTaskEvent";var c=[],b={},d={},e=[],f=new a.AOMFileHandler;a.AOMHelper.isTitaniumApp()&&(f=new a.AOMFileHandlerTi);a.AOMHelper.addEventListener(a.AOMNetworkHandler.AOMNETWORKEVENT,function(a){q()});var g=function(a,b,c,d){f.readFile(a,function(a){a&&JSON.parse(a);
c&&c()},function(b){console.error("Error on restoring content of "+a+" --\x3e "+b.code);d&&d(b)})},q=function(){if(1>c.length)b={},s();else if(!1!==a.AOMNetworkHandler.isConnected()){var d=c.shift();delete e[d.localId];t();f.readFile(d.fileKey,function(a){f.removeFile(d.fileKey);if(a&&!1===d.isStaticData){var b=new d.clazz;b.fromJson(a);a=b}(a||d.isStaticData&&d.url)&&n(d,a,d.isStaticData,!0)},function(a){console.error("Error occured on reading file "+a)})}},l={extCallback:void 0,onOk:function(a){if(l.extCallback&&
l.extCallback.onOk)l.extCallback.onOk(a);q()},onError:function(a){if(l.extCallback&&l.extCallback.onError)l.extCallback.onError(a);q()}},n=function(c,e,f){var g=c.url,n=void 0!=c.refName&&0<c.refName.length;switch(c.httpMethod){case "POST":n&&!1===f&&(g=g.substring(g.lastIndexOf("/")+1),C(e),g=b[g]+"/"+c.refName);l.extCallback={onOk:function(e){if(null!=e&&0<e.length){b[c.localId]=e;s();if(!1===f){var g=c.localId;if((model=d[g])&&model.isOffline())delete d[g],model.data.href=e,model.setOffline(!1)}a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c,href:e})}},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c,href:k})}};g?f?a.Datastore.getInstance().postStaticDataOnServerWithHref(e,g,l,!0):a.Datastore.getInstance().postOnServer(e,l,g,!0):a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:error,info:c,href:k});break;case "PUT":var k=C(e);void 0!==k&&0<k.length?(l.extCallback={onOk:function(){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c})},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c})}},a.Datastore.getInstance().updateOnServer(e,l,!0)):a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:a.Status.HREF_NOT_FOUND,info:c});break;case "DELETE":k=void 0,k=f?K(g):C(e),n&&(g=g.substring(g.lastIndexOf("/")+1),k=b[g]+"/"+c.refName+"/"+k.substring(k.lastIndexOf("/")+1)),k&&0<k.length?(l.extCallback={onOk:function(){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c})},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c})}},n||f?a.Datastore.getInstance().deleteOnServer(k,!0,l):a.Datastore.getInstance().deleteModelOnServer(e,!0,l)):a.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:a.Status.HREF_NOT_FOUND,info:c})}},k=function(){for(var b=0,c=Math.floor(1E6*Math.random()+1);e[c]&&5>b;)b++,c=Math.floor(1E6*Math.random()+1);if(4<=b)throw new a.ApiomatRequestError(a.Status.TOO_MANY_LOCALIDS);
return c},C=function(a){var c=a.getHref();if(a.isOffline()){var d=a.getID();if(void 0!==d&&0<d.length&&(d=b[d]))c=d,a.data.href=c;for(var e in a.data)e.endsWith("URL")&&(d=K(a.data[e]))&&(a.data[e]=d)}return c},K=function(a){a=a.substring(a.lastIndexOf("/")+1);return b[a]},s=function(){return f.writeFile(a.AOMFileHandler.HREFMAP_FILENAME,JSON.stringify(b))},t=function(){f.writeFile(a.AOMFileHandler.USEDLOCALIDS_FILENAME,JSON.stringify(e));f.writeFile(a.AOMFileHandler.TASKLIST_FILENAME,JSON.stringify(c))},
D=function(b,c,d,e){var g=void 0;f.getSizeOfAppDir(function(k){k&&k>=1024*this.cacheSizeInMB?(console.error("Max cache size is reached. Can't add to cache!"),e&&e(new a.ApiomatRequestError(a.Status.MAX_CACHE_SIZE_REACHED))):(g=f.createFileName(c),f.writeFile(g,b||"",function(){d&&d(g)},function(b){console.error("Can't persist to cache: "+b.code);e&&e(new a.ApiomatRequestError(a.Status.CANT_WRITE_IN_CACHE))}))})};this.cacheSizeInMB=4;this.addTask=function(b,e,f,g,l,n){var p=e,q=!1===f instanceof a.AbstractClientDataModel,
s=f;!1===q&&(s=f.toJson());var x=void 0;if("POST"===b){try{x=k()}catch(C){throw C;}-1===p.indexOf("/",this.length-1)&&(p+="/");p+=(g?g+"/":"")+x;!1===q&&(d[x]=f)}D(s,x||b,function(d){d&&(d=new a.AOMOfflineInfo(b,e,d,f?f.constructor:void 0,x,g,q),c.push(d),t());l&&l(p)},function(a){console.error("Got error on adding task to offline queue: "+a);n&&n(a)})};this.init=function(d,f){var k=function(){g(a.AOMFileHandler.USEDLOCALIDS_FILENAME,e,function(){q();"undefined"!==typeof d&&d()},function(a){"undefined"!==
typeof f&&f(a)})},l=function(){g(a.AOMFileHandler.HREFMAP_FILENAME,b,function(){k()},function(a){k()})};g(a.AOMFileHandler.TASKLIST_FILENAME,c,function(){l()},function(a){l()})};this.isConnected=function(){return a.AOMNetworkHandler.isConnected()};this.clearCache=function(){b={};s();for(var a=0,e=c.length;a<e;a++){var g=c[a];g.fileKey&&f.removeFile(g.fileKey)}d={};c=[];t()}}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Role={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Role=function(){this.init()};a.Role.getRoles=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.Role,c,b,!1,d)};a.Role.getRolesAndRefHref=function(c,b,d,e){a.Datastore.getInstance().loadListFromServerWithClass(a.Role,c,b,d,e)};a.Role.getRolesCount=function(c,b,d){a.Datastore.getInstance().loadCountFromServer(a.Role,void 0,c,b,d)};a.Role.deleteAllFromStorage=function(c,b){a.Datastore.getInstance().deleteCollectionFromStorage(!1,a.Role,c,b)};a.Role.deleteAllFromStorageWithReferencedHrefs=
function(c,b){a.Datastore.getInstance().deleteCollectionFromStorage(!0,a.Role,c,b)};a.Role.prototype=new a.AbstractClientDataModel;a.Role.prototype.constructor=a.Role;a.Role.prototype.init=function(){this.data={}};a.Role.prototype.getSimpleName=function(){return"Role"};a.Role.prototype.getModuleName=function(){return"Basics"};a.Role.prototype.getMembers=function(){return this.data.members};a.Role.prototype.setMembers=function(a){this.data.members=a};a.Role.prototype.getName=function(){return null!==
this.data.name?this.data.name:void 0};a.Role.prototype.setName=function(a){this.data.name=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.User={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.User=function(c,b){this.init();"undefined"!==typeof c&&this.setUserName(c);"undefined"!==typeof b&&this.setPassword(b);this.initDatastoreIfNeeded=function(b){if(!1===a.Datastore.isInstantiated())if("undefined"!==typeof this.getUserName()&&"undefined"!==typeof this.getPassword())a.Datastore.configureWithCredentials(this);else if("getSessionToken"in this&&"undefined"!==typeof this.getSessionToken()&&this.getSessionToken())a.Datastore.configureWithSessionToken(this.getSessionToken());
else if("undefined"!==typeof b&&b)a.Datastore.configurePlain(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS);else throw Error("The Datastore needs to be configured with user credentials or a session token for this method to work.");};this.save=function(b,c){this.initDatastoreIfNeeded(!1);a.AbstractClientDataModel.prototype.save.apply(this,[b,c])};this.requestNewPassword=function(b,c){a.Datastore.getInstance().postOnServer(this,{onOk:function(b){a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,
b)}},"models/requestResetPassword/",b)};this.resetPasswordAsync=function(b,c){a.Datastore.getInstance().postOnServer(this,b,"models/requestResetPassword/",c)};this.resetPassword=function(a,b,c){this.changePassword(a,b,c)};this.changePassword=function(b,c,f){if(this.getCurrentState==a.ObjectState.PERSISTING)a.Datastore.negativeCallback(c,error);else{var g={onOk:function(){this.parent.setOffline(this.wasLocalSave||!1);a.Datastore.configure(this.parent);a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,
b)},parent:this};this.setPassword(b);a.Datastore.getInstance().shouldSendOffline("PUT")?(g.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("PUT",this.getHref(),this,void 0,g)):a.Datastore.getInstance().updateOnServer(this,g,f)}};this.requestSessionToken=function(a,b,c,g){this.requestSessionTokenWithRefreshToken(void 0,a,b,!1,c,g)};this.requestSessionTokenWithRefreshToken=function(b,c,f,g,q,l){b=b||void 0;this.initDatastoreIfNeeded("undefined"===b?!1:!0);var n=f;"undefined"!==typeof c&&c&&(n=
{onOk:function(b){var c=b.sessionToken||"";""===c?a.Datastore.negativeCallback(f,new a.ApiomatRequestError(a.Status.NO_TOKEN_RECEIVED,200)):(this.parent.setSessionToken(c),a.Datastore.configureWithUserSessionToken(this.parent),a.Datastore.positiveCallback(f,b))},onError:function(b){a.Datastore.negativeCallback(f,b)},parent:this});"undefined"===typeof b?a.Datastore.getInstance().requestSessionToken(n,g,q,l):a.Datastore.getInstance().requestSessionTokenWithRefreshToken(b,n,g,q,l)}};a.User.AOMBASEURL=
"http://172.16.42.148:8081/yambas/rest/apps/AMAG0";a.User.AOMAPIKEY="1067066393892665148";a.User.AOMSYS="LIVE";a.User.AOMSDKVERSION="2.4.7-18";a.User.getUsers=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.User,c,b,!1,d)};a.User.getUsersAndRefHref=function(c,b,d,e){a.Datastore.getInstance().loadListFromServerWithClass(a.User,c,b,d,e)};a.User.getUsersCount=function(c,b,d){a.Datastore.getInstance().loadCountFromServer(a.User,void 0,c,b,d)};a.User.deleteAllFromStorage=function(c,
b){a.Datastore.getInstance().deleteCollectionFromStorage(!1,a.User,c,b)};a.User.deleteAllFromStorageWithReferencedHrefs=function(c,b){a.Datastore.getInstance().deleteCollectionFromStorage(!0,a.User,c,b)};a.User.prototype=new a.AbstractClientDataModel;a.User.prototype.constructor=a.User;a.User.prototype.loadMe=function(c,b){this.initDatastoreIfNeeded(!1);a.Datastore.getInstance().loadFromServer("models/me",c,this,!1,void 0,void 0,!1,b)};a.User.prototype.init=function(){this.data={};this.data.dynamicAttributes=
{}};a.User.prototype.getSimpleName=function(){return"User"};a.User.prototype.getModuleName=function(){return"Basics"};a.User.prototype.getDateOfBirth=function(){var a=this.data.dateOfBirth;return"undefined"!=typeof a?new Date(a):void 0};a.User.prototype.setDateOfBirth=function(a){this.data.dateOfBirth=null!=a&&void 0!=a?a.getTime():null};a.User.prototype.getFirstName=function(){return null!==this.data.firstName?this.data.firstName:void 0};a.User.prototype.setFirstName=function(a){this.data.firstName=
a};a.User.prototype.getLastName=function(){return null!==this.data.lastName?this.data.lastName:void 0};a.User.prototype.setLastName=function(a){this.data.lastName=a};a.User.prototype.getLocLatitude=function(){var a=this.data.loc;if(a)return a[0]};a.User.prototype.getLocLongitude=function(){var a=this.data.loc;if(a)return a[1]};a.User.prototype.setLocLatitude=function(a){var b=this.data.loc;b?b[0]=a:b=[a,void 0];this.data.loc=b};a.User.prototype.setLocLongitude=function(a){var b=this.data.loc;b?b[1]=
a:b=[0,a];this.data.loc=b};a.User.prototype.getPassword=function(){return null!==this.data.password?this.data.password:void 0};a.User.prototype.setPassword=function(a){this.data.password=a};a.User.prototype.getSalt=function(){return null!==this.data.salt?this.data.salt:void 0};a.User.prototype.setSalt=function(a){this.data.salt=a};a.User.prototype.getSessionToken=function(){return null!==this.data.sessionToken?this.data.sessionToken:void 0};a.User.prototype.setSessionToken=function(a){this.data.sessionToken=
a};a.User.prototype.getUserName=function(){return null!==this.data.userName?this.data.userName:void 0};a.User.prototype.setUserName=function(a){this.data.userName=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AMAGUser={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AMAGUser=function(a,b){this.init();"undefined"!==typeof a&&this.setUserName(a);"undefined"!==typeof b&&this.setPassword(b)};a.AMAGUser.getAMAGUsers=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.AMAGUser,c,b,!1,d)};a.AMAGUser.getAMAGUsersAndRefHref=function(c,b,d,e){a.Datastore.getInstance().loadListFromServerWithClass(a.AMAGUser,c,b,d,e)};a.AMAGUser.getAMAGUsersCount=function(c,b,d){a.Datastore.getInstance().loadCountFromServer(a.AMAGUser,void 0,c,b,d)};a.AMAGUser.deleteAllFromStorage=
function(c,b){a.Datastore.getInstance().deleteCollectionFromStorage(!1,a.AMAGUser,c,b)};a.AMAGUser.deleteAllFromStorageWithReferencedHrefs=function(c,b){a.Datastore.getInstance().deleteCollectionFromStorage(!0,a.AMAGUser,c,b)};a.AMAGUser.prototype=new a.User;a.AMAGUser.prototype.constructor=a.AMAGUser;a.AMAGUser.prototype.init=function(){a.User.prototype.init.call(this);this.data.dynamicAttributes={}};a.AMAGUser.prototype.getSimpleName=function(){return"AMAGUser"};a.AMAGUser.prototype.getModuleName=
function(){return"AMAGPhonebook"};a.AMAGUser.prototype.getAddressCity=function(){return null!==this.data.addressCity?this.data.addressCity:void 0};a.AMAGUser.prototype.setAddressCity=function(a){this.data.addressCity=a};a.AMAGUser.prototype.getAddressStreet=function(){return null!==this.data.addressStreet?this.data.addressStreet:void 0};a.AMAGUser.prototype.setAddressStreet=function(a){this.data.addressStreet=a};a.AMAGUser.prototype.getAddressStreetNumber=function(){return null!==this.data.addressStreetNumber?
this.data.addressStreetNumber:void 0};a.AMAGUser.prototype.setAddressStreetNumber=function(a){this.data.addressStreetNumber=a};a.AMAGUser.prototype.getAddressZipcode=function(){return null!==this.data.addressZipcode?this.data.addressZipcode:void 0};a.AMAGUser.prototype.setAddressZipcode=function(a){this.data.addressZipcode=a};a.AMAGUser.prototype.getEmail=function(){return null!==this.data.email?this.data.email:void 0};a.AMAGUser.prototype.setEmail=function(a){this.data.email=a};a.AMAGUser.prototype.getInitials=
function(){return null!==this.data.initials?this.data.initials:void 0};a.AMAGUser.prototype.setInitials=function(a){this.data.initials=a};a.AMAGUser.prototype.getLanguage=function(){return null!==this.data.language?this.data.language:void 0};a.AMAGUser.prototype.setLanguage=function(a){this.data.language=a};a.AMAGUser.prototype.getMobile=function(){return null!==this.data.mobile?this.data.mobile:void 0};a.AMAGUser.prototype.setMobile=function(a){this.data.mobile=a};a.AMAGUser.prototype.getOrganization=
function(){return null!==this.data.organization?this.data.organization:void 0};a.AMAGUser.prototype.setOrganization=function(a){this.data.organization=a};a.AMAGUser.prototype.getTelephone=function(){return null!==this.data.telephone?this.data.telephone:void 0};a.AMAGUser.prototype.setTelephone=function(a){this.data.telephone=a}})("undefined"===typeof exports?Apiomat:exports);